import { createContext, useContext, useEffect, useState } from "react";

/* =========================================================
   THÈME (clair / sombre) — appliqué globalement via une
   classe sur <html> ("light" ou "dark"). Défaut : sombre.
   ========================================================= */
const ThemeContext = createContext(null);

export function ThemeProvider({ children }) {
  const [theme, setTheme] = useState(() => localStorage.getItem("theme") || "dark");

  useEffect(() => {
    const root = document.documentElement;
    root.classList.remove("light", "dark");
    root.classList.add(theme);
    localStorage.setItem("theme", theme);
  }, [theme]);

  const toggleTheme = () => setTheme((t) => (t === "dark" ? "light" : "dark"));

  return (
    <ThemeContext.Provider value={{ theme, setTheme, toggleTheme }}>
      {children}
    </ThemeContext.Provider>
  );
}

export function useTheme() {
  const ctx = useContext(ThemeContext);
  // Valeur de repli si le provider n'est pas monté (évite un crash)
  return ctx || { theme: "dark", setTheme: () => {}, toggleTheme: () => {} };
}

/* =========================================================
   LANGUES (MG / FR / ANG) — FR par défaut.
   Dictionnaire à plat : clés "namespace.cle".
   ========================================================= */
export const LANGUAGES = [
  { code: "fr", label: "Français", short: "FR" },
  { code: "mg", label: "Malagasy", short: "MG" },
  { code: "en", label: "English", short: "ANG" },
];

const translations = {
  fr: {
    "app.tagline": "Plateforme citoyenne",
    "user.default": "Utilisateur",

    "nav.home": "Accueil",
    "nav.report": "Signaler",
    "nav.profile": "Profil",
    "nav.dashboard": "Dashboard",
    "nav.signalements": "Signalements",
    "nav.users": "Utilisateurs",
    "nav.assignmentIA": "Assignation IA",

    "desc.overview": "Vue d'ensemble",
    "desc.explore": "Explorer",
    "desc.new": "Nouveau",
    "desc.myAccount": "Mon compte",
    "desc.management": "Gestion",
    "desc.settings": "Paramètres",
    "desc.ai": "Intelligence artificielle",
    "desc.missions": "Mes missions",

    "role.admin": "Admin",
    "role.agent": "Agent",
    "role.citizen": "Citoyen",
    "roleFull.admin": "Administrateur",
    "roleFull.agent": "Agent terrain",
    "roleFull.citizen": "Citoyen",

    "notif.title": "Notifications",
    "notif.refresh": "Rafraîchir",
    "notif.readAll": "Tout lire",
    "notif.empty": "Aucune notification",

    "menu.logout": "Déconnexion",
    "menu.appearance": "Apparence",
    "menu.language": "Langue",
    "menu.light": "Clair",
    "menu.dark": "Sombre",

    "logout.title": "Déconnexion",
    "logout.question": "Êtes-vous sûr de vouloir vous déconnecter ?",
    "common.cancel": "Annuler",
    "common.loading": "Chargement",

    "sig.newTitle": "Nouveau signalement",
    "sig.editTitle": "Modifier le signalement",
    "sig.subtitle": "Signalez un problème à Madagascar",
    "sig.titlePlaceholder": "Titre du signalement *",
    "sig.descPlaceholder": "Description détaillée *",
    "sig.locLabel": "Localisation précise *",
    "sig.detectGps": "Détecter ma position GPS",
    "sig.detecting": "Détection en cours...",
    "sig.manualEntry": "Saisir manuellement l'adresse",
    "sig.manualTitle": "Saisie manuelle",
    "sig.quartier": "Quartier",
    "sig.street": "Rue / Route",
    "sig.city": "Ville",
    "sig.validateAddress": "Valider l'adresse",
    "sig.detected": "Localisation détectée",
    "sig.lowPrecisionWarn": "Précision faible : le quartier détecté peut être inexact. Si ce n'est pas le bon, utilisez « Saisir manuellement l'adresse » pour le corriger.",
    "sig.lowPrecisionMsg": "La précision est faible (fréquent sur ordinateur, où la position vient du Wi-Fi). Vérifiez le quartier détecté et corrigez-le au besoin avec « Saisir manuellement l'adresse ».",
    "sig.entered": "Adresse saisie",
    "sig.clear": "Effacer",
    "sig.imagesLabel": "Images",
    "sig.atLeastOne": "(au moins 1)",
    "sig.takePhoto": "Prendre une photo",
    "sig.gallery": "Galerie / Fichiers",
    "sig.orUrl": "ou via une URL",
    "sig.urlPlaceholder": "URL de l'image",
    "sig.capture": "Capturer",
    "sig.send": "Envoyer",
    "sig.sending": "Envoi en cours...",
    "sig.update": "Mettre à jour",
    "sig.searchPlaceholder": "Rechercher un signalement...",
    "sig.filterType": "Type de problème",
    "sig.filterStatus": "Statut",
    "sig.all": "Tous",
    "sig.reset": "Réinitialiser",
    "sig.results": "résultat(s)",
    "sig.listTitle": "Tous les signalements",
    "sig.empty": "Aucun signalement trouvé",
    "sig.seeMore": "Voir plus",
    "sig.descrTitle": "Description",
    "sig.locationTitle": "Localisation",
    "sig.date": "Date",
    "sig.author": "Auteur",
    "sig.edit": "Modifier",
    "sig.delete": "Supprimer",
    "sig.gps": "Coordonnées GPS",
    "sig.anonymous": "Anonyme",
    "sig.deleteConfirm": "Êtes-vous sûr de vouloir supprimer ce signalement ?",
    "sig.close": "Fermer",
    "sig.success": "Succès",
    "sig.info": "Information",
    "sig.confirmation": "Confirmation",
    "sig.createdOk": "✓ Signalement créé avec succès !",
    "sig.updatedOk": "✓ Signalement modifié avec succès !",
    "sig.deletedOk": "✓ Signalement supprimé avec succès !",
    "sig.fixErrors": "Veuillez corriger les erreurs",

    "status.EN_ATTENTE": "En attente",
    "status.EN_COURS": "En cours",
    "status.RESOLU": "Résolu",
    "status.REJETE": "Rejeté",
    "status.TRAITE": "Traité",

    "cat.VOIRIE": "Voirie / Routes",
    "cat.ECLAIRAGE": "Éclairage Public",
    "cat.PROPRETE": "Propreté / Déchets",
    "cat.EAU": "Eau / Assainissement",
    "cat.ESPACES_VERTS": "Espaces verts",
    "cat.TRANSPORTS": "Transports / Mobilité",
    "cat.SECURITE": "Sécurité / Prévention",
    "cat.URBANISME": "Urbanisme",

    "feed.reportsWord": "signalements",
    "feed.resolved": "Résolus",
    "feed.handling": "Prise en charge",
    "feed.resolution": "Résolution",
    "feed.empty": "Aucun signalement",
    "feed.beFirst": "Soyez le premier à signaler un problème",
    "feed.comment": "Commenter",
    "feed.share": "Partager",
    "feed.noComment": "Aucun commentaire",
    "feed.writeComment": "Écrire un commentaire...",
    "feed.shareTo": "Envoyer à un utilisateur",
    "feed.searchUser": "Rechercher un utilisateur...",
    "feed.noUser": "Aucun utilisateur trouvé",
    "feed.location": "Localisation",
    "feed.recently": "Récemment",
    "feed.selectRecipient": "Veuillez sélectionner au moins un destinataire",

    "prof.title": "Mon profil",
    "prof.subtitle": "Gérez vos informations",
    "prof.edit": "Modifier",
    "prof.save": "Enregistrer",
    "prof.loading": "Chargement...",
    "prof.fullName": "Nom complet",
    "prof.email": "Email",
    "prof.fullAddress": "Adresse complète",
    "prof.yourName": "Votre nom",
    "prof.yourAddress": "Votre adresse complète",
    "prof.security": "Sécurité",
    "prof.change": "Changer",
    "prof.currentPassword": "Mot de passe actuel",
    "prof.newPassword": "Nouveau mot de passe",
    "prof.confirmPassword": "Confirmer le mot de passe",
    "prof.addressNotSet": "Adresse non renseignée",
    "prof.unknownLocation": "Localisation inconnue",
    "prof.justNow": "À l'instant",
    "prof.updated": "Profil mis à jour !",
    "prof.passwordChanged": "Mot de passe changé !",
    "prof.reportDeleted": "Signalement supprimé !",
    "prof.fixErrors": "Veuillez corriger les erreurs avant de valider",
    "prof.networkError": "Erreur réseau",
    "prof.passwordMismatch": "Les mots de passe ne correspondent pas",
    "prof.reports": "Signalements",
    "prof.myReports": "Mes signalements",
    "prof.personalInfo": "Informations personnelles",
    "prof.notProvided": "Non renseigné",
    "prof.roleNotEditable": "Rôle non modifiable",
    "prof.updateError": "Erreur lors de la mise à jour",
    "prof.passwordChangeError": "Erreur lors du changement de mot de passe",
    "prof.deleteReportTitle": "Supprimer le signalement",
    "prof.deleteConfirm": "Êtes-vous sûr de vouloir supprimer « {title} » ? Cette action est irréversible.",

    "time.now": "À l'instant",
    "time.minutes": "Il y a {n} min",
    "time.hours": "Il y a {n} h",
    "time.days": "Il y a {n} j",

    "type.VOIRIE": "Voirie",
    "type.ECLAIRAGE": "Éclairage",
    "type.DECHETS": "Déchets",
    "type.PROPRETE": "Déchets",
    "type.EAU": "Eau",
    "type.ESPACES_VERTS": "Espaces verts",
    "type.SECURITE": "Sécurité",
    "type.TRANSPORTS": "Transports",
    "type.URBANISME": "Urbanisme",
    "type.AUTRE": "Autre",

    "notifT.NOUVEAU_SIGNALEMENT": "Nouveau signalement",
    "notifT.CONFIRMATION_SIGNALEMENT": "Signalement enregistré",
    "notifT.ASSIGNATION": "Signalement assigné",
    "notifT.CHANGEMENT_STATUS": "Mise à jour de votre signalement",
    "notifT.AGENT_ASSIGNE": "Agent assigné",
    "notifT.PARTAGE_SIGNALEMENT": "Signalement partagé",
    "notifM.NOUVEAU_SIGNALEMENT": "Un nouveau signalement a été créé : {title}",
    "notifM.CONFIRMATION_SIGNALEMENT": "Votre signalement « {title} » a bien été enregistré et sera traité rapidement.",
    "notifM.ASSIGNATION": "Le signalement « {title} » vous a été assigné.",
    "notifM.AGENT_ASSIGNE": "Un agent a été assigné à votre signalement « {title} » : {agent}",
    "notifM.CHANGEMENT_STATUS": "Votre signalement « {title} » {status}",
    "notifM.PARTAGE_SIGNALEMENT": "{sender} a partagé le signalement « {title} » avec vous.",
    "statusPhrase.EN_COURS": "est maintenant en cours de traitement",
    "statusPhrase.RESOLU": "a été résolu ! Merci pour votre contribution.",
    "statusPhrase.REJETE": "a été rejeté.",

    "auth.accessBadge": "ACCÈS",
    "auth.loginTitle": "Connexion",
    "auth.loginSubtitle": "Connectez-vous pour accéder à votre compte",
    "auth.email": "Adresse email",
    "auth.password": "Mot de passe",
    "auth.loginBtn": "Se connecter",
    "auth.loggingIn": "Connexion en cours...",
    "auth.noAccount": "Pas encore de compte ?",
    "auth.signup": "Inscrivez-vous",
    "auth.registerBadge": "INSCRIPTION",
    "auth.registerTitle": "Créer un compte",
    "auth.registerSubtitle": "Rejoignez la communauté en quelques secondes",
    "auth.registerBtn": "Créer mon compte",
    "auth.registering": "Inscription en cours...",
    "auth.wrongCredentials": "Email ou mot de passe incorrect",
    "auth.forgotPassword": "Mot de passe oublié ?",
    "auth.sending": "Envoi...",
    "auth.sendCode": "Envoyer le code",
    "auth.resendCode": "Renvoyer",
    "auth.confirm": "Confirmer",
    "auth.codePlaceholder": "Code à 6 chiffres",
    "auth.codeSent": "Un code de vérification a été envoyé à votre email.",
    "auth.codeSendError": "Impossible d'envoyer le code. Réessayez.",
    "auth.codeInvalid": "Code incorrect ou expiré.",
    "auth.emailInvalid": "Adresse email invalide.",
    "auth.emailConfirmed": "Email confirmé",
    "auth.confirmEmailFirst": "Confirmez d'abord votre adresse email.",
    "auth.resetSent": "Si un compte existe pour cette adresse, un email de réinitialisation a été envoyé.",
    "reset.title": "Nouveau mot de passe",
    "reset.subtitle": "Choisissez un nouveau mot de passe pour votre compte.",
    "reset.newPassword": "Nouveau mot de passe",
    "reset.confirmPassword": "Confirmer le mot de passe",
    "reset.submit": "Réinitialiser le mot de passe",
    "reset.mismatch": "Les mots de passe ne correspondent pas.",
    "reset.invalidLink": "Lien invalide ou expiré.",
    "reset.error": "La réinitialisation a échoué. Réessayez.",
    "reset.successTitle": "Mot de passe réinitialisé !",
    "reset.successMsg": "Redirection vers la page de connexion...",
    "reset.backToLogin": "Retour à la connexion",
    "auth.hasAccount": "Déjà un compte ?",
    "auth.login": "Connectez-vous",
    "auth.brandLine1": "Rejoignez la",
    "auth.brandLine2": "révolution urbaine",
    "auth.brandParagraph": "Participez activement à l'amélioration de votre ville en signalant les problèmes et en contribuant à une communauté plus responsable.",
    "auth.statRealtime": "Temps réel",
    "auth.statTracking": "Suivi",
    "auth.statCommunity": "Communauté",
    "auth.fullName": "Nom complet",
    "auth.phone": "Téléphone",
    "auth.phoneFormat": "Format: 0321234567 (10 chiffres)",
    "auth.address": "Adresse complète",
    "auth.accountType": "Type de compte",
    "auth.citizen": "Citoyen",
    "auth.agent": "Agent Municipal",
    "auth.citizenDesc": "Signalez des problèmes dans votre quartier",
    "auth.agentDesc": "Gérez et résolvez les signalements citoyens",
    "auth.interventionDomain": "Domaine d'intervention",
    "auth.yourJob": "Votre métier",
    "dom.VOIRIE.label": "Voirie et infrastructures",
    "dom.VOIRIE.desc": "Routes, trottoirs, nids-de-poule",
    "dom.ECLAIRAGE.label": "Éclairage public",
    "dom.ECLAIRAGE.desc": "Lampadaires, éclairage urbain",
    "dom.DECHETS.label": "Déchets et Propreté",
    "dom.DECHETS.desc": "Collecte des déchets, nettoyage",
    "dom.ESPACES_VERTS.label": "Espaces verts",
    "dom.ESPACES_VERTS.desc": "Parcs, jardins, arbres",
    "dom.TRANSPORTS.label": "Transports et mobilité",
    "dom.TRANSPORTS.desc": "Transports en commun, stationnement",
    "dom.SECURITE.label": "Sécurité et prévention",
    "dom.SECURITE.desc": "Sécurité publique, prévention",
    "dom.URBANISME.label": "Urbanisme",
    "dom.URBANISME.desc": "Aménagement urbain, construction",
    "met.AGENT_VOIRIE.label": "Agent de voirie",
    "met.AGENT_VOIRIE.desc": "Réparation nids-de-poule, entretien chaussées",
    "met.TECHNICIEN_GENIE_CIVIL.label": "Technicien génie civil",
    "met.TECHNICIEN_GENIE_CIVIL.desc": "Inspection ponts, tunnels, ouvrages d'art",
    "met.CHEF_CHANTIER_VOIRIE.label": "Chef de chantier voirie",
    "met.CHEF_CHANTIER_VOIRIE.desc": "Coordination travaux routiers",
    "met.AGENT_SIGNALISATION.label": "Agent de signalisation",
    "met.AGENT_SIGNALISATION.desc": "Pose et entretien panneaux, feux tricolores",
    "met.TECHNICIEN_ECLAIRAGE.label": "Technicien éclairage",
    "met.TECHNICIEN_ECLAIRAGE.desc": "Réparation lampadaires, entretien du réseau",
    "met.INGENIEUR_ECLAIRAGE.label": "Ingénieur éclairage urbain",
    "met.INGENIEUR_ECLAIRAGE.desc": "Conception schéma d'éclairage, optimisation énergétique",
    "met.AGENT_MAINTENANCE_ELEC.label": "Agent maintenance électrique",
    "met.AGENT_MAINTENANCE_ELEC.desc": "Dépannage pannes électriques",
    "met.AGENT_COLLECTE.label": "Agent de collecte",
    "met.AGENT_COLLECTE.desc": "Ramassage ordures ménagères",
    "met.TECHNICIEN_NETTOIEMENT.label": "Technicien nettoiement",
    "met.TECHNICIEN_NETTOIEMENT.desc": "Nettoyage rues, espaces publics",
    "met.RESPONSABLE_DECHETTERIE.label": "Responsable déchetterie",
    "met.RESPONSABLE_DECHETTERIE.desc": "Gestion des déchèteries",
    "met.AGENT_TRI.label": "Agent de tri",
    "met.AGENT_TRI.desc": "Centre de tri des déchets",
    "met.COORDINATEUR_PROPRETE.label": "Coordinateur propreté",
    "met.COORDINATEUR_PROPRETE.desc": "Planification tournées",
    "met.JARDINIER_MUNICIPAL.label": "Jardinier municipal",
    "met.JARDINIER_MUNICIPAL.desc": "Entretien parcs, jardins, massifs",
    "met.ELAGUEUR.label": "Élagueur",
    "met.ELAGUEUR.desc": "Taille et entretien arbres",
    "met.TECHNICIEN_ESPACES_VERTS.label": "Technicien espaces verts",
    "met.TECHNICIEN_ESPACES_VERTS.desc": "Aménagement paysager",
    "met.PAYSAGISTE_URBAIN.label": "Paysagiste urbain",
    "met.PAYSAGISTE_URBAIN.desc": "Conception espaces verts",
    "met.AGENT_ARROSAGE.label": "Agent arrosage",
    "met.AGENT_ARROSAGE.desc": "Gestion système d'irrigation",
    "met.AGENT_REGULATION.label": "Agent de régulation",
    "met.AGENT_REGULATION.desc": "Gestion trafic, feux, bouchons",
    "met.CONTROLEUR_TRANSPORT.label": "Contrôleur transport",
    "met.CONTROLEUR_TRANSPORT.desc": "Contrôle bus, tramway, métro",
    "met.TECHNICIEN_STATIONNEMENT.label": "Technicien stationnement",
    "met.TECHNICIEN_STATIONNEMENT.desc": "Gestion parkings, horodateurs",
    "met.AGENT_MOBILITE_DOUCE.label": "Agent mobilité douce",
    "met.AGENT_MOBILITE_DOUCE.desc": "Entretien pistes cyclables, bornes vélos",
    "met.AGENT_SECURITE_URBAINE.label": "Agent de sécurité urbaine",
    "met.AGENT_SECURITE_URBAINE.desc": "Surveillance quartiers",
    "met.POLICE_MUNICIPALE.label": "Police municipale",
    "met.POLICE_MUNICIPALE.desc": "Maintien ordre public, verbalisation",
    "met.AGENT_MEDIATEUR.label": "Agent médiateur",
    "met.AGENT_MEDIATEUR.desc": "Gestion conflits de quartier",
    "met.COORDINATEUR_VIDEO.label": "Coordinateur vidéoprotection",
    "met.COORDINATEUR_VIDEO.desc": "Supervision caméras",
    "met.URBANISTE.label": "Urbaniste",
    "met.URBANISTE.desc": "Planification urbaine",
    "met.ARCHITECTE_CONSEIL.label": "Architecte conseil",
    "met.ARCHITECTE_CONSEIL.desc": "Conseil en architecture",
    "met.TECHNICIEN_URBANISME.label": "Technicien urbanisme",
    "met.TECHNICIEN_URBANISME.desc": "Instruction permis de construire",
    "met.CHARGE_MISSION_URBAIN.label": "Chargé de mission urbain",
    "met.CHARGE_MISSION_URBAIN.desc": "Projets d'aménagement",

    "common.error": "Erreur",
    "common.success": "Succès",
    "common.info": "Information",
    "common.limit": "Limite",
    "common.requiredField": "Champ requis",
    "common.networkError": "Erreur réseau",
    "common.genericError": "Une erreur est survenue",
    "common.congrats": "Félicitations !",
    "common.search": "Rechercher",
    "agent.welcome": "Bienvenue dans votre espace de travail",
    "agent.toTreat": "Signalements à traiter",
    "agent.assigned": "Assignés",
    "agent.assignedReports": "Signalements assignés",
    "agent.processingReports": "Signalements en traitement",
    "agent.noAssigned": "Aucun signalement assigné",
    "agent.allTreated": "Tous vos signalements ont été traités !",
    "agent.noAssignedYet": "Vous n'avez pas encore de signalements à traiter.",
    "agent.noReportsToShow": "Aucun signalement à afficher",
    "agent.loadingDashboard": "Chargement du tableau de bord...",
    "agent.loadingReports": "Chargement des signalements...",
    "agent.totalActive": "Total actifs",
    "agent.urgent": "Urgent",
    "agent.important": "Important",
    "agent.moderate": "Modéré",
    "agent.low": "Faible",
    "agent.municipalService": "Service municipal",
    "agent.notDefined": "Non défini",
    "agent.noTitle": "Sans titre",
    "agent.noDescription": "Aucune description",
    "agent.locationUnspecified": "Localisation non spécifiée",
    "agent.unknownDate": "Date inconnue",
    "agent.unknown": "Inconnu",
    "agent.proofTitle": "Preuve de résolution",
    "agent.proofIntro": "Veuillez fournir une preuve que le problème a été résolu.",
    "agent.proofDescLabel": "Description de la résolution",
    "agent.proofDescPlaceholder": "Décrivez comment le problème a été résolu...",
    "agent.beforeAfter": "Photos avant/après",
    "agent.clickAddPhotos": "Cliquez pour ajouter des photos",
    "agent.cantLoadReports": "Impossible de charger les signalements",
    "agent.cantReachServer": "Impossible de contacter le serveur",
    "agent.takenCharge": "Signalement pris en charge !",
    "agent.cantTakeCharge": "Impossible de prendre en charge",
    "agent.max5photos": "5 photos maximum",
    "agent.cantLoadImages": "Impossible de charger les images",
    "agent.addDescription": "Ajoutez une description",
    "agent.proofSendError": "Erreur lors de l'envoi de la preuve",
    "agent.statusUpdateError": "Erreur lors de la mise à jour du statut",
    "agent.reportResolved": "Signalement résolu !",
    "agent.resolvedReports": "Signalements Résolus",
    "agent.resolvedSubtitle": "Consultez les preuves de résolution des signalements",
    "agent.totalResolved": "Total résolus",
    "agent.myResolution": "Ma résolution",
    "agent.searchResolvedPlaceholder": "Rechercher par titre, description ou adresse...",
    "agent.noneResolvedYet": "Vous n'avez pas encore résolu de signalement",
    "agent.noResolvedFound": "Aucun signalement résolu trouvé",
    "agent.resolvedBy": "Résolu par :",
    "agent.seeLess": "Voir moins",
    "agent.seeProofs": "Voir les preuves de résolution",
    "agent.noImageForProof": "Aucune image pour cette preuve",
    "agent.noProofRecorded": "Aucune preuve d'intervention enregistrée",

    "admin.overview": "Vue d'ensemble de la plateforme SmartCity",
    "admin.unspecified": "Non spécifiée",
    "admin.cantFetchReports": "Impossible de récupérer les signalements",
    "admin.loadDataError": "Erreur lors du chargement des données",
    "admin.selectAgent": "Veuillez sélectionner un agent",
    "admin.cantAssign": "Impossible d'assigner",
    "admin.assignNetworkError": "Erreur réseau lors de l'assignation",
    "admin.fillAllFields": "Veuillez remplir tous les champs",
    "admin.addError": "Erreur lors de l'ajout",
    "admin.printPreview": "Aperçu avant impression",
    "admin.pdfPrint": "PDF / Impression",
    "admin.topAgents": "Top Agents",
    "admin.topAgentsSub": "Classés par signalements traités (en cours + résolus)",
    "admin.noActiveAgent": "Aucun agent actif pour le moment",
    "admin.topCitizens": "Top Citoyens",
    "admin.topCitizensSub": "Classés par signalements créés",
    "admin.noActiveCitizen": "Aucun citoyen actif pour le moment",
    "admin.allAgents": "Tous les agents",
    "admin.allCitizens": "Tous les citoyens",
    "admin.email": "Email",
    "admin.phone": "Téléphone",
    "admin.domain": "Domaine",
    "admin.job": "Métier",
    "admin.totalHandled": "Total traités",
    "admin.signupDate": "Date inscription",
    "admin.accessDenied": "Accès Refusé",
    "admin.adminOnly": "Cette page est réservée aux administrateurs.",
    "admin.aiSuggestions": "Suggestions IA",
    "admin.aiPriority": "Priorité: géographique + disponibilité",
    "admin.noAgentForDomain": "Aucun agent disponible pour ce domaine",
    "admin.pendingReports": "Signalements en attente",
    "admin.availableAgents": "Agents disponibles",
    "admin.expertiseDomains": "Domaines d'expertise",
    "admin.searchToAssign": "Rechercher un signalement par titre, description, quartier ou ville...",
    "admin.noReportToAssign": "Aucun signalement à assigner",
    "admin.allAssignedOrResolved": "Tous les signalements ont été assignés ou résolus",
    "admin.citizenReports": "Signalements citoyens",
    "admin.citizenReportsSub": "Consultez tous les problèmes signalés par la communauté",
    "admin.searchByTitle": "Rechercher par titre, description ou localisation...",
    "admin.filters": "Filtres",
    "admin.publishDate": "Date de publication",
    "admin.publishedBy": "Publié par",
    "agent.dashboardTitle": "Dashboard Agent",
    "agent.assignedCaps": "SIGNALEMENTS ASSIGNÉS",
    "agent.seeAll": "Voir tous",
    "agent.toTakeCharge": "À prendre en charge",
    "agent.activeReports": "SIGNALEMENTS ACTIFS",
    "agent.sortedByDanger": "Classés par niveau de dangerosité (du plus urgent au moins urgent)",
    "agent.sortedByDate": "Classés par date (du plus récent au plus ancien)",
    "agent.byDate": "Organisée par Date le plus récent",
    "agent.byAI": "Organisée par IA - Dangerosité",
    "agent.inProgressShort": "en cours",
    "agent.resolvedShort": "résolus",
    "agent.treatedShort": "traités",
    "agent.reportsShort": "signalements",
    "agent.takeCharge": "Prendre en charge",
    "agent.markResolved": "Marquer résolu",
    "agent.viewMore": "Voir plus",
    "agent.detailsTitle": "Détails du signalement",
    "agent.locationTitle": "Localisation",
    "agent.getDirections": "Itinéraire",
    "agent.openInMaps": "Ouvrir dans Maps",
    "agent.noCoordinates": "Coordonnées GPS non disponibles pour ce signalement",
    "agent.createdOn": "Créé le",
    "agent.latestAssigned": "Derniers signalements assignés",
    "agent.seeAllShort": "Voir tout",
    "common.confirm": "Confirmer",
    "admin.assignToAgent": "Assigner à un agent",
    "admin.reportAddress": "Adresse du signalement",
    "admin.suggestWithAI": "Suggérer avec l'IA",
    "admin.allAvailableAgents": "Tous les agents disponibles",
    "admin.aiAnalyzing": "Analyse IA en cours...",
    "admin.seeUrgent": "Voir tous les signalements urgents",
    "admin.colName": "Nom",
    "prof.min6": "minimum 6 caractères",
    "val.passwordMin6": "Le mot de passe doit contenir au moins 6 caractères",
    "val.required": "Ce champ est requis",
    "val.titleRequired": "Le titre est requis",
    "val.titleMin3": "Le titre doit contenir au moins 3 caractères",
    "val.titleMax100": "Le titre ne doit pas dépasser 100 caractères",
    "val.descRequired": "La description est requise",
    "val.descMin10": "La description doit contenir au moins 10 caractères",
    "val.descMax500": "La description ne doit pas dépasser 500 caractères",
    "val.imageUrlInvalid": "L'URL de l'image n'est pas valide",
    "val.imageRequired": "Au moins une image est obligatoire",
    "feed.sendToPrefix": "Envoyer à",
    "feed.user": "utilisateur",
    "feed.users": "utilisateurs",
    "feed.sending": "Envoi...",
    "prof.password": "Mot de passe",
    "prof.dangerZone": "Zone de danger",
    "prof.deleteWarning": "La suppression de votre compte est définitive et irréversible.",
    "prof.deleteAccount": "Supprimer mon compte",
    "prof.deleteConfirm": "Êtes-vous sûr ? Votre compte sera supprimé définitivement. Cette action est irréversible.",
    "prof.deleteConfirmBtn": "Oui, supprimer",
    "prof.deleteError": "La suppression du compte a échoué. Veuillez réessayer.",
    "val.invalidFormat": "Format invalide",
    "val.addressRequired": "L'adresse est obligatoire",
    "val.addressMin4": "L'adresse doit contenir au moins 4 caractères",
    "val.phoneRequired": "Le numéro de téléphone est obligatoire",
    "val.phoneFormat": "Le téléphone doit commencer par 032, 033, 034, 037 ou 038 et contenir exactement 10 chiffres",
    "val.nameMin2": "Le nom doit contenir au moins 2 caractères",
    "val.emailInvalid": "Email invalide (exemple: nom@domaine.com)",
    "val.nameRequired": "Le nom est requis",
    "val.nameNoDigits": "Le nom ne doit pas contenir de chiffres",
    "val.nameLetters": "Le nom ne doit contenir que des lettres, espaces ou tirets",
    "val.emailRequired": "L'email est requis",
    "val.emailGmail": "L'email doit être une adresse @gmail.com",
    "val.emailNoSpaces": "L'email ne doit pas contenir d'espaces",
    "val.passwordRequired": "Le mot de passe est requis",
    "auth.oops": "Oups !",
    "auth.continue": "Continuer",
    "auth.loginSuccessMsg": "Connexion réussie ! Bienvenue",
    "auth.accountCreated": "Votre compte a été créé avec succès ! Vous pouvez maintenant vous connecter.",
    "val.addressMin6": "L'adresse doit contenir au moins 6 caractères",
    "val.addressChars": "L'adresse ne doit contenir que des lettres, chiffres et espaces",
    "val.nameNoDigitsDot": "Le nom ne doit pas contenir de chiffres.",
    "val.nameLettersDot": "Le nom ne doit contenir que des lettres, espaces ou tirets.",
    "val.selectDomain": "Veuillez sélectionner votre domaine d'intervention",
    "val.selectJob": "Veuillez sélectionner votre métier",
    "admin.urgentToTreat": "signalement(s) urgent(s) à traiter",
    "admin.noUrgent": "Aucun signalement urgent",
    "chat.title": "Messages",
    "chat.received": "Messages reçus",
    "chat.newMessage": "Nouveau message",
    "chat.noMessage": "Aucun message",
    "chat.recipient": "Destinataire",
    "chat.selectRecipient": "Sélectionner un destinataire",
    "chat.recipientLocked": "Destinataire verrouillé (réponse en cours)",
    "chat.sendType": "Type d'envoi",
    "chat.message": "Message",
    "chat.email": "Email",
    "chat.subject": "Sujet",
    "chat.subjectPlaceholder": "Sujet du message",
    "chat.yourMessage": "Votre message...",
    "chat.infoCitizen": "💬 En tant que citoyen, vous pouvez uniquement envoyer des messages aux administrateurs.",
    "chat.infoAgent": "💬 En tant qu'agent, vous pouvez uniquement envoyer des messages aux administrateurs.",
    "chat.infoAdmin": "💬 En tant qu'administrateur, vous pouvez envoyer des messages à tous les utilisateurs (citoyens, agents, admins).",
    "chat.invalidRecipient": "❌ Destinataire invalide.",
    "chat.sendReply": "Envoyer la réponse",
    "chat.sendMessage": "Envoyer le message",
    "chat.sendEmail": "Envoyer l'email",
    "chat.replyAdminOnly": "Vous ne pouvez répondre qu'aux messages des administrateurs.",
    "chat.sendAdminOnly": "Vous ne pouvez envoyer des messages qu'aux administrateurs uniquement.",
    "chat.emailSent": "Email envoyé avec succès ! Le destinataire recevra une notification et un email réel.",
    "chat.messageSent": "Message envoyé avec succès !",
    "chat.sendError": "Erreur lors de l'envoi",
    "map.title": "🗺️ Carte des signalements",
    "map.comingSoon": "Fonctionnalité à venir...",
    "map.subtitle": "Visualisation des signalements sur une carte interactive",
    "mine.empty": "Vous n'avez aucun signalement",
    "mine.noPosition": "Position non définie",
    "admin.colTitle": "Titre",
    "admin.colType": "Type",
    "admin.colLocation": "Localisation",
    "admin.colStatus": "Statut",
    "admin.colDate": "Date",
    "prof.lastModified": "Dernière modification :",
    "prof.never": "Jamais",
    "prof.phone": "Téléphone",
    "admin.dashboardTitle": "Tableau de bord",
    "admin.export": "Exporter",
    "admin.totalReports": "Total signalements",
    "admin.resolutionRate": "Taux de résolution",
    "admin.activeAgents": "Agents actifs",
    "admin.byProblemType": "Par type de problème",
    "admin.urgentReports": "Signalements urgents",
    "admin.latestReports": "Derniers signalements",
    "admin.assignAgent": "Assigner un agent",
    "admin.assigning": "Assignation...",
    "admin.assign": "Assigner",
    "admin.personalSpace": "Espace Personnel",
    "admin.fullNameCaps": "NOM COMPLET",
    "admin.emailCaps": "ADRESSE EMAIL",
    "admin.roleCaps": "RÔLE",
    "admin.changePassword": "Changer le mot de passe",
    "admin.encrypted": "Protégé par chiffrement AES-256",
    "admin.smartAssignment": "ASSIGNATION INTELLIGENTE",
    "admin.aiAssignmentTitle": "Assignation par IA",
    "admin.aiAssignmentSub": "L'intelligence artificielle analyse chaque signalement et suggère l'agent le plus adapté selon la localisation et la disponibilité",
    "admin.allDomains": "Tous les domaines",
    "admin.noAgentForType": "Aucun agent disponible pour ce type de problème",
    "admin.aiError": "Erreur lors de l'analyse IA",
    "admin.assignedTo": "Signalement assigné à",
    "admin.assignError": "Erreur lors de l'assignation",
    "admin.networkError": "Erreur réseau",
    "admin.aiFoundPrefix": "L'IA a trouvé",
    "admin.agentsWord": "agent(s)",
    "admin.inSameCity": "dans la même ville",
    "admin.availableWord": "disponible(s)",
    "admin.userManagement": "Gestion des utilisateurs",
    "admin.agentsWord": "agents",
    "admin.citizensWord": "citoyens",
  },

  mg: {
    "app.tagline": "Sehatra ho an'ny olom-pirenena",
    "user.default": "Mpampiasa",

    "nav.home": "Fandraisana",
    "nav.report": "Hitatitra",
    "nav.profile": "Mombamomba",
    "nav.dashboard": "Tabilao",
    "nav.signalements": "Fitarainana",
    "nav.users": "Mpampiasa",
    "nav.assignmentIA": "Fanendrena AI",

    "desc.overview": "Topimaso",
    "desc.explore": "Hijery",
    "desc.new": "Vaovao",
    "desc.myAccount": "Ny kaontiko",
    "desc.management": "Fitantanana",
    "desc.settings": "Kirakira",
    "desc.ai": "Faharaitsaina artifisialy",
    "desc.missions": "Ny asako",

    "role.admin": "Admin",
    "role.agent": "Mpiasa",
    "role.citizen": "Olom-pirenena",
    "roleFull.admin": "Mpitantana",
    "roleFull.agent": "Mpiasa an-tanety",
    "roleFull.citizen": "Olom-pirenena",

    "notif.title": "Fampandrenesana",
    "notif.refresh": "Havaozina",
    "notif.readAll": "Vakio daholo",
    "notif.empty": "Tsy misy fampandrenesana",

    "menu.logout": "Hivoaka",
    "menu.appearance": "Endrika",
    "menu.language": "Fiteny",
    "menu.light": "Mazava",
    "menu.dark": "Maizina",

    "logout.title": "Hivoaka",
    "logout.question": "Tena te-hivoaka ve ianao ?",
    "common.cancel": "Aoka ihany",
    "common.loading": "Eo am-pakàna",

    "sig.newTitle": "Fitarainana vaovao",
    "sig.editTitle": "Hanova ny fitarainana",
    "sig.subtitle": "Mitatera olana eto Madagasikara",
    "sig.titlePlaceholder": "Lohatenin'ny fitarainana *",
    "sig.descPlaceholder": "Famaritana amin'ny an-tsipiriany *",
    "sig.locLabel": "Toerana marina *",
    "sig.detectGps": "Hikaroka ny toerako (GPS)",
    "sig.detecting": "Eo am-pikarohana...",
    "sig.manualEntry": "Manorata ny adiresy an-tanana",
    "sig.manualTitle": "Fanoratana an-tanana",
    "sig.quartier": "Fokontany",
    "sig.street": "Lalana",
    "sig.city": "Tanàna",
    "sig.validateAddress": "Ekeo ny adiresy",
    "sig.detected": "Toerana hita",
    "sig.lowPrecisionWarn": "Marika kely: mety tsy marina ny fokontany hita. Raha toa ka diso, ampiasao « Manorata ny adiresy an-tanana » hanitsiana azy.",
    "sig.lowPrecisionMsg": "Ambany ny fahamarinana (matetika amin'ny ordinateur, izay avy amin'ny Wi-Fi ny toerana). Hamarino ny fokontany hita ary ahitsio raha ilaina amin'ny « Manorata ny adiresy an-tanana ».",
    "sig.entered": "Adiresy voasoratra",
    "sig.clear": "Fafao",
    "sig.imagesLabel": "Sary",
    "sig.atLeastOne": "(1 farafahakeliny)",
    "sig.takePhoto": "Maka sary",
    "sig.gallery": "Tahiry / Rakitra",
    "sig.orUrl": "na amin'ny URL",
    "sig.urlPlaceholder": "URL-n'ny sary",
    "sig.capture": "Raiso",
    "sig.send": "Alefaso",
    "sig.sending": "Andefasana...",
    "sig.update": "Hanavao",
    "sig.searchPlaceholder": "Hikaroka fitarainana...",
    "sig.filterType": "Karazana olana",
    "sig.filterStatus": "Sata",
    "sig.all": "Rehetra",
    "sig.reset": "Averina",
    "sig.results": "valiny",
    "sig.listTitle": "Fitarainana rehetra",
    "sig.empty": "Tsy misy fitarainana hita",
    "sig.seeMore": "Hijery bebe kokoa",
    "sig.descrTitle": "Famaritana",
    "sig.locationTitle": "Toerana",
    "sig.date": "Daty",
    "sig.author": "Mpanoratra",
    "sig.edit": "Hanova",
    "sig.delete": "Hamafa",
    "sig.gps": "Toerana GPS",
    "sig.anonymous": "Tsy fantatra",
    "sig.deleteConfirm": "Tena te-hamafa ity fitarainana ity ve ianao ?",
    "sig.close": "Hidiana",
    "sig.success": "Fahombiazana",
    "sig.info": "Fampahalalana",
    "sig.confirmation": "Fanamafisana",
    "sig.createdOk": "✓ Voaforona soa aman-tsara ny fitarainana !",
    "sig.updatedOk": "✓ Voaova soa aman-tsara ny fitarainana !",
    "sig.deletedOk": "✓ Voafafa soa aman-tsara ny fitarainana !",
    "sig.fixErrors": "Ahitsio ny diso azafady",

    "status.EN_ATTENTE": "Miandry",
    "status.EN_COURS": "Am-pandehanana",
    "status.RESOLU": "Voavaha",
    "status.REJETE": "Nolavina",
    "status.TRAITE": "Vita",

    "cat.VOIRIE": "Lalana",
    "cat.ECLAIRAGE": "Jiro an-dalambe",
    "cat.PROPRETE": "Fahadiovana / Fako",
    "cat.EAU": "Rano / Fanadiovana",
    "cat.ESPACES_VERTS": "Zaridaina",
    "cat.TRANSPORTS": "Fitaterana",
    "cat.SECURITE": "Fiarovana",
    "cat.URBANISME": "Fanajariana tanàna",

    "feed.reportsWord": "fitarainana",
    "feed.resolved": "Voavaha",
    "feed.handling": "Fandraisana an-tanana",
    "feed.resolution": "Famahana",
    "feed.empty": "Tsy misy fitarainana",
    "feed.beFirst": "Aoka ho voalohany hitatitra olana",
    "feed.comment": "Haneho hevitra",
    "feed.share": "Zarao",
    "feed.noComment": "Tsy misy hevitra",
    "feed.writeComment": "Manorata hevitra...",
    "feed.shareTo": "Alefaso amin'ny mpampiasa",
    "feed.searchUser": "Hikaroka mpampiasa...",
    "feed.noUser": "Tsy misy mpampiasa hita",
    "feed.location": "Toerana",
    "feed.recently": "Vao haingana",
    "feed.selectRecipient": "Misafidiana mpandray iray farafahakeliny azafady",

    "prof.title": "Ny mombamomba ahy",
    "prof.subtitle": "Tantano ny mombamomba anao",
    "prof.edit": "Hanova",
    "prof.save": "Tehirizo",
    "prof.loading": "Eo am-pakàna...",
    "prof.fullName": "Anarana feno",
    "prof.email": "Mailaka",
    "prof.fullAddress": "Adiresy feno",
    "prof.yourName": "Ny anaranao",
    "prof.yourAddress": "Ny adiresinao feno",
    "prof.security": "Fiarovana",
    "prof.change": "Ovay",
    "prof.currentPassword": "Teny miafina ankehitriny",
    "prof.newPassword": "Teny miafina vaovao",
    "prof.confirmPassword": "Hamafiso ny teny miafina",
    "prof.addressNotSet": "Tsy voasoratra ny adiresy",
    "prof.unknownLocation": "Toerana tsy fantatra",
    "prof.justNow": "Vao izao",
    "prof.updated": "Voaova ny mombamomba !",
    "prof.passwordChanged": "Voaova ny teny miafina !",
    "prof.reportDeleted": "Voafafa ny fitarainana !",
    "prof.fixErrors": "Ahitsio ny diso alohan'ny hanamarina",
    "prof.networkError": "Olana amin'ny fifandraisana",
    "prof.passwordMismatch": "Tsy mifanaraka ny teny miafina",
    "prof.reports": "Fitarainana",
    "prof.myReports": "Ny fitarainako",
    "prof.personalInfo": "Mombamomba manokana",
    "prof.notProvided": "Tsy voafeno",
    "prof.roleNotEditable": "Andraikitra tsy azo ovaina",
    "prof.updateError": "Nisy olana tamin'ny fanavaozana",
    "prof.passwordChangeError": "Nisy olana tamin'ny fanovana teny miafina",
    "prof.deleteReportTitle": "Hamafa ny fitarainana",
    "prof.deleteConfirm": "Tena te-hamafa « {title} » ve ianao ? Tsy azo ovaina intsony izany.",

    "time.now": "Vao izao",
    "time.minutes": "{n} min lasa",
    "time.hours": "{n} ora lasa",
    "time.days": "{n} andro lasa",

    "type.VOIRIE": "Lalana",
    "type.ECLAIRAGE": "Jiro",
    "type.DECHETS": "Fako",
    "type.PROPRETE": "Fako",
    "type.EAU": "Rano",
    "type.ESPACES_VERTS": "Zaridaina",
    "type.SECURITE": "Fiarovana",
    "type.TRANSPORTS": "Fitaterana",
    "type.URBANISME": "Tanàna",
    "type.AUTRE": "Hafa",

    "notifT.NOUVEAU_SIGNALEMENT": "Fitarainana vaovao",
    "notifT.CONFIRMATION_SIGNALEMENT": "Voarakitra ny fitarainana",
    "notifT.ASSIGNATION": "Fitarainana nomena",
    "notifT.CHANGEMENT_STATUS": "Fanavaozana ny fitarainanao",
    "notifT.AGENT_ASSIGNE": "Mpiasa nomena",
    "notifT.PARTAGE_SIGNALEMENT": "Fitarainana nozaraina",
    "notifM.NOUVEAU_SIGNALEMENT": "Misy fitarainana vaovao : {title}",
    "notifM.CONFIRMATION_SIGNALEMENT": "Voarakitra soa aman-tsara ny fitarainanao « {title} » ary ho karakaraina haingana.",
    "notifM.ASSIGNATION": "Nomena anao ny fitarainana « {title} ».",
    "notifM.AGENT_ASSIGNE": "Nisy mpiasa nomena ho an'ny fitarainanao « {title} » : {agent}",
    "notifM.CHANGEMENT_STATUS": "Ny fitarainanao « {title} » {status}",
    "notifM.PARTAGE_SIGNALEMENT": "Nozarain'i {sender} taminao ny fitarainana « {title} ».",
    "statusPhrase.EN_COURS": "efa am-pandehanana izao",
    "statusPhrase.RESOLU": "voavaha ! Misaotra noho ny fandraisanao anjara.",
    "statusPhrase.REJETE": "nolavina.",

    "auth.accessBadge": "FIDIRANA",
    "auth.loginTitle": "Fidirana",
    "auth.loginSubtitle": "Midira mba hahazoana miditra amin'ny kaontinao",
    "auth.email": "Adiresy mailaka",
    "auth.password": "Teny miafina",
    "auth.loginBtn": "Hiditra",
    "auth.loggingIn": "Eo am-pidirana...",
    "auth.noAccount": "Mbola tsy manana kaonty ?",
    "auth.signup": "Hisoratra anarana",
    "auth.registerBadge": "FISORATANA ANARANA",
    "auth.registerTitle": "Hamorona kaonty",
    "auth.registerSubtitle": "Midira ao amin'ny vondrom-piarahamonina afaka segondra vitsy",
    "auth.registerBtn": "Hamorona ny kaontiko",
    "auth.registering": "Eo am-pisoratana...",
    "auth.wrongCredentials": "Diso ny mailaka na ny teny miafina",
    "auth.forgotPassword": "Hadino ny teny miafina ?",
    "auth.sending": "Andefasana...",
    "auth.sendCode": "Alefaso ny kaody",
    "auth.resendCode": "Alefaso indray",
    "auth.confirm": "Hamafiso",
    "auth.codePlaceholder": "Kaody isa 6",
    "auth.codeSent": "Nalefa tany amin'ny mailakao ny kaody fanamarinana.",
    "auth.codeSendError": "Tsy afaka nandefa ny kaody. Andramo indray.",
    "auth.codeInvalid": "Diso na lany daty ny kaody.",
    "auth.emailInvalid": "Tsy mety ny adiresy mailaka.",
    "auth.emailConfirmed": "Voamarina ny mailaka",
    "auth.confirmEmailFirst": "Hamarino aloha ny adiresy mailakao.",
    "auth.resetSent": "Raha misy kaonty amin'ity adiresy ity, dia nisy mailaka famerenana nalefa.",
    "reset.title": "Teny miafina vaovao",
    "reset.subtitle": "Misafidiana teny miafina vaovao ho an'ny kaontinao.",
    "reset.newPassword": "Teny miafina vaovao",
    "reset.confirmPassword": "Hamafiso ny teny miafina",
    "reset.submit": "Avereno ny teny miafina",
    "reset.mismatch": "Tsy mifanaraka ny teny miafina.",
    "reset.invalidLink": "Rohy tsy mety na lany daty.",
    "reset.error": "Tsy nahomby ny famerenana. Andramo indray.",
    "reset.successTitle": "Voaova ny teny miafina !",
    "reset.successMsg": "Ho entina any amin'ny fidirana ianao...",
    "reset.backToLogin": "Hiverina amin'ny fidirana",
    "auth.hasAccount": "Efa manana kaonty ?",
    "auth.login": "Hiditra",
    "auth.brandLine1": "Mikambana amin'ny",
    "auth.brandLine2": "revolisiona an-tanàn-dehibe",
    "auth.brandParagraph": "Mandraisa anjara mavitrika amin'ny fampandrosoana ny tanànanao amin'ny fitaterana olana sy ny fandraisana anjara amin'ny vondrom-piarahamonina tompon'andraikitra kokoa.",
    "auth.statRealtime": "Fotoana tena izy",
    "auth.statTracking": "Fanaraha-maso",
    "auth.statCommunity": "Vondrom-piarahamonina",
    "auth.fullName": "Anarana feno",
    "auth.phone": "Finday",
    "auth.phoneFormat": "Endrika: 0321234567 (isa 10)",
    "auth.address": "Adiresy feno",
    "auth.accountType": "Karazana kaonty",
    "auth.citizen": "Olom-pirenena",
    "auth.agent": "Mpiasam-panjakana",
    "auth.citizenDesc": "Mitatera olana ao amin'ny fokontaninao",
    "auth.agentDesc": "Tantano sy vahao ny fitarainan'ny mponina",
    "auth.interventionDomain": "Sehatra iasana",
    "auth.yourJob": "Ny asanao",
    "dom.VOIRIE.label": "Lalana sy fotodrafitrasa",
    "dom.VOIRIE.desc": "Lalana, arabe, lavaka",
    "dom.ECLAIRAGE.label": "Jiro an-dalambe",
    "dom.ECLAIRAGE.desc": "Fanazavana, jiro an-tanàna",
    "dom.DECHETS.label": "Fako sy Fahadiovana",
    "dom.DECHETS.desc": "Fanangonana fako, fanadiovana",
    "dom.ESPACES_VERTS.label": "Zaridaina",
    "dom.ESPACES_VERTS.desc": "Valan-javaboary, zaridaina, hazo",
    "dom.TRANSPORTS.label": "Fitaterana",
    "dom.TRANSPORTS.desc": "Fitaterana iombonana, fijanonana",
    "dom.SECURITE.label": "Filaminana sy fisorohana",
    "dom.SECURITE.desc": "Filaminam-bahoaka, fisorohana",
    "dom.URBANISME.label": "Fanajariana tanàna",
    "dom.URBANISME.desc": "Fanajariana tanàna, fananganana",
    "met.AGENT_VOIRIE.label": "Mpiasan-dalana",
    "met.AGENT_VOIRIE.desc": "Fanamboarana lavaka, fikojakojana arabe",
    "met.TECHNICIEN_GENIE_CIVIL.label": "Teknisiana génie civil",
    "met.TECHNICIEN_GENIE_CIVIL.desc": "Fisavana tetezana, tonelina, asa vaventy",
    "met.CHEF_CHANTIER_VOIRIE.label": "Lehiben'ny toeram-piasana lalana",
    "met.CHEF_CHANTIER_VOIRIE.desc": "Fandrindrana asa fanamboaran-dalana",
    "met.AGENT_SIGNALISATION.label": "Mpiasan'ny famantarana",
    "met.AGENT_SIGNALISATION.desc": "Fametrahana takelaka, jiro fifamoivoizana",
    "met.TECHNICIEN_ECLAIRAGE.label": "Teknisiana jiro",
    "met.TECHNICIEN_ECLAIRAGE.desc": "Fanamboarana jiro, fikojakojana tambajotra",
    "met.INGENIEUR_ECLAIRAGE.label": "Injenieran'ny jiro an-tanàna",
    "met.INGENIEUR_ECLAIRAGE.desc": "Famolavolana drafitra jiro, fanatsarana angovo",
    "met.AGENT_MAINTENANCE_ELEC.label": "Mpiasan'ny herinaratra",
    "met.AGENT_MAINTENANCE_ELEC.desc": "Fanamboarana simba herinaratra",
    "met.AGENT_COLLECTE.label": "Mpanangona fako",
    "met.AGENT_COLLECTE.desc": "Fanangonana fako an-trano",
    "met.TECHNICIEN_NETTOIEMENT.label": "Teknisiana fanadiovana",
    "met.TECHNICIEN_NETTOIEMENT.desc": "Fanadiovana arabe sy toerana ho an'ny daholobe",
    "met.RESPONSABLE_DECHETTERIE.label": "Tompon'andraikitry ny fanariam-pako",
    "met.RESPONSABLE_DECHETTERIE.desc": "Fitantanana toeram-panariam-pako",
    "met.AGENT_TRI.label": "Mpanavaka fako",
    "met.AGENT_TRI.desc": "Ivo-toerana fanavahana fako",
    "met.COORDINATEUR_PROPRETE.label": "Mpandrindra fahadiovana",
    "met.COORDINATEUR_PROPRETE.desc": "Fandaharana dia",
    "met.JARDINIER_MUNICIPAL.label": "Mpikarakara zaridaina",
    "met.JARDINIER_MUNICIPAL.desc": "Fikojakojana valan-javaboary sy zaridaina",
    "met.ELAGUEUR.label": "Mpandidy hazo",
    "met.ELAGUEUR.desc": "Fandidiana sy fikojakojana hazo",
    "met.TECHNICIEN_ESPACES_VERTS.label": "Teknisiana zaridaina",
    "met.TECHNICIEN_ESPACES_VERTS.desc": "Fanajariana zaridaina",
    "met.PAYSAGISTE_URBAIN.label": "Mpamolavola zaridaina",
    "met.PAYSAGISTE_URBAIN.desc": "Famolavolana zaridaina",
    "met.AGENT_ARROSAGE.label": "Mpandena zaridaina",
    "met.AGENT_ARROSAGE.desc": "Fitantanana rafitra fandenana",
    "met.AGENT_REGULATION.label": "Mpandrindra fifamoivoizana",
    "met.AGENT_REGULATION.desc": "Fitantanana fifamoivoizana, jiro, fitohanana",
    "met.CONTROLEUR_TRANSPORT.label": "Mpanara-maso fitaterana",
    "met.CONTROLEUR_TRANSPORT.desc": "Fanaraha-maso fiara fitateram-bahoaka",
    "met.TECHNICIEN_STATIONNEMENT.label": "Teknisiana fijanonana",
    "met.TECHNICIEN_STATIONNEMENT.desc": "Fitantanana toeram-pijanonana",
    "met.AGENT_MOBILITE_DOUCE.label": "Mpiasan'ny fifamoivoizana malefaka",
    "met.AGENT_MOBILITE_DOUCE.desc": "Fikojakojana lalana bisikileta",
    "met.AGENT_SECURITE_URBAINE.label": "Mpiambina an-tanàna",
    "met.AGENT_SECURITE_URBAINE.desc": "Fiambenana fokontany",
    "met.POLICE_MUNICIPALE.label": "Polisim-monina",
    "met.POLICE_MUNICIPALE.desc": "Fitandroana ny filaminam-bahoaka",
    "met.AGENT_MEDIATEUR.label": "Mpanelanelana",
    "met.AGENT_MEDIATEUR.desc": "Fandaminana ady an-tanàna",
    "met.COORDINATEUR_VIDEO.label": "Mpandrindra fanaraha-maso video",
    "met.COORDINATEUR_VIDEO.desc": "Fanaraha-maso fakan-tsary",
    "met.URBANISTE.label": "Mpandrindra tanàna",
    "met.URBANISTE.desc": "Fandrindrana tanàna",
    "met.ARCHITECTE_CONSEIL.label": "Mpanolotsaina maritrano",
    "met.ARCHITECTE_CONSEIL.desc": "Torohevitra momba ny maritrano",
    "met.TECHNICIEN_URBANISME.label": "Teknisiana fanajariana tanàna",
    "met.TECHNICIEN_URBANISME.desc": "Fandinihana fahazoan-dàlana hanorina",
    "met.CHARGE_MISSION_URBAIN.label": "Tompon'andraikitra fampandrosoana an-tanàna",
    "met.CHARGE_MISSION_URBAIN.desc": "Tetikasa fanajariana",

    "common.error": "Hadisoana",
    "common.success": "Fahombiazana",
    "common.info": "Fampahalalana",
    "common.limit": "Fetra",
    "common.requiredField": "Saha ilaina",
    "common.networkError": "Olana amin'ny fifandraisana",
    "common.genericError": "Nisy olana nitranga",
    "common.congrats": "Arahaba !",
    "common.search": "Hikaroka",
    "agent.welcome": "Tongasoa eto amin'ny sehatra fiasanao",
    "agent.toTreat": "Fitarainana hokarakaraina",
    "agent.assigned": "Nomena",
    "agent.assignedReports": "Fitarainana nomena",
    "agent.processingReports": "Fitarainana karakaraina",
    "agent.noAssigned": "Tsy misy fitarainana nomena",
    "agent.allTreated": "Voakarakara avokoa ny fitarainanao !",
    "agent.noAssignedYet": "Mbola tsy manana fitarainana hokarakaraina ianao.",
    "agent.noReportsToShow": "Tsy misy fitarainana aseho",
    "agent.loadingDashboard": "Eo am-pakàna ny tabilao...",
    "agent.loadingReports": "Eo am-pakàna ny fitarainana...",
    "agent.totalActive": "Isany",
    "agent.urgent": "Maika",
    "agent.important": "Zava-dehibe",
    "agent.moderate": "Antonony",
    "agent.low": "Ambany",
    "agent.municipalService": "Sampan-draharaham-monina",
    "agent.notDefined": "Tsy voafaritra",
    "agent.noTitle": "Tsy misy lohateny",
    "agent.noDescription": "Tsy misy famaritana",
    "agent.locationUnspecified": "Toerana tsy voalaza",
    "agent.unknownDate": "Daty tsy fantatra",
    "agent.unknown": "Tsy fantatra",
    "agent.proofTitle": "Porofon'ny famahana",
    "agent.proofIntro": "Manomeza porofo fa voavaha ny olana.",
    "agent.proofDescLabel": "Famaritana ny famahana",
    "agent.proofDescPlaceholder": "Lazao ny fomba namahana ny olana...",
    "agent.beforeAfter": "Sary talohan'ny/aorian'ny",
    "agent.clickAddPhotos": "Tsindrio hanampy sary",
    "agent.cantLoadReports": "Tsy afaka naka ny fitarainana",
    "agent.cantReachServer": "Tsy afaka nifandray tamin'ny serivera",
    "agent.takenCharge": "Noraisina an-tanana ny fitarainana !",
    "agent.cantTakeCharge": "Tsy afaka nandray an-tanana",
    "agent.max5photos": "Sary 5 fara-fahabetsany",
    "agent.cantLoadImages": "Tsy afaka naka ny sary",
    "agent.addDescription": "Manampia famaritana",
    "agent.proofSendError": "Nisy olana tamin'ny fandefasana ny porofo",
    "agent.statusUpdateError": "Nisy olana tamin'ny fanavaozana ny sata",
    "agent.reportResolved": "Voavaha ny fitarainana !",
    "agent.resolvedReports": "Fitarainana voavaha",
    "agent.resolvedSubtitle": "Jereo ny porofon'ny famahana ny fitarainana",
    "agent.totalResolved": "Totalin'ny voavaha",
    "agent.myResolution": "Ny famahako",
    "agent.searchResolvedPlaceholder": "Hikaroka amin'ny lohateny, famaritana na adiresy...",
    "agent.noneResolvedYet": "Mbola tsy nisy fitarainana novahanao",
    "agent.noResolvedFound": "Tsy misy fitarainana voavaha hita",
    "agent.resolvedBy": "Novahan'i :",
    "agent.seeLess": "Hijery vitsy",
    "agent.seeProofs": "Hijery ny porofon'ny famahana",
    "agent.noImageForProof": "Tsy misy sary ho an'ity porofo ity",
    "agent.noProofRecorded": "Tsy misy porofo voarakitra",

    "admin.overview": "Topimaso ny sehatra SmartCity",
    "admin.unspecified": "Tsy voalaza",
    "admin.cantFetchReports": "Tsy afaka naka ny fitarainana",
    "admin.loadDataError": "Nisy olana tamin'ny fakàna ny angona",
    "admin.selectAgent": "Misafidiana mpiasa iray azafady",
    "admin.cantAssign": "Tsy afaka nanendry",
    "admin.assignNetworkError": "Olana amin'ny fifandraisana tamin'ny fanendrena",
    "admin.fillAllFields": "Fenoy daholo ny saha azafady",
    "admin.addError": "Nisy olana tamin'ny fanampiana",
    "admin.printPreview": "Topimaso alohan'ny hanontana",
    "admin.pdfPrint": "PDF / Fanontana",
    "admin.topAgents": "Mpiasa voalohany",
    "admin.topAgentsSub": "Milahatra araka ny fitarainana voakarakara (am-pandehanana + voavaha)",
    "admin.noActiveAgent": "Tsy misy mpiasa mavitrika amin'izao",
    "admin.topCitizens": "Olom-pirenena voalohany",
    "admin.topCitizensSub": "Milahatra araka ny fitarainana noforonina",
    "admin.noActiveCitizen": "Tsy misy olom-pirenena mavitrika amin'izao",
    "admin.allAgents": "Ny mpiasa rehetra",
    "admin.allCitizens": "Ny olom-pirenena rehetra",
    "admin.email": "Mailaka",
    "admin.phone": "Finday",
    "admin.domain": "Sehatra",
    "admin.job": "Asa",
    "admin.totalHandled": "Totalin'ny voakarakara",
    "admin.signupDate": "Daty nisoratana",
    "admin.accessDenied": "Lavina ny fidirana",
    "admin.adminOnly": "Voatokana ho an'ny mpitantana ihany ity pejy ity.",
    "admin.aiSuggestions": "Soso-kevitra AI",
    "admin.aiPriority": "Laharam-pahamehana: jeografika + fahafahana",
    "admin.noAgentForDomain": "Tsy misy mpiasa misy ho an'ity sehatra ity",
    "admin.pendingReports": "Fitarainana miandry",
    "admin.availableAgents": "Mpiasa misy",
    "admin.expertiseDomains": "Sehatra manam-pahaizana",
    "admin.searchToAssign": "Hikaroka fitarainana amin'ny lohateny, famaritana, fokontany na tanàna...",
    "admin.noReportToAssign": "Tsy misy fitarainana hendrena",
    "admin.allAssignedOrResolved": "Voatendry na voavaha avokoa ny fitarainana",
    "admin.citizenReports": "Fitarainan'ny mponina",
    "admin.citizenReportsSub": "Jereo ny olana rehetra notaterin'ny vondrom-piarahamonina",
    "admin.searchByTitle": "Hikaroka amin'ny lohateny, famaritana na toerana...",
    "admin.filters": "Sivana",
    "admin.publishDate": "Daty namoahana",
    "admin.publishedBy": "Navoakan'i",
    "agent.dashboardTitle": "Tabilaon'ny mpiasa",
    "agent.assignedCaps": "FITARAINANA NOMENA",
    "agent.seeAll": "Hijery daholo",
    "agent.toTakeCharge": "Horaisina an-tanana",
    "agent.activeReports": "FITARAINANA MAVITRIKA",
    "agent.sortedByDanger": "Milahatra araka ny haavon'ny loza (manomboka amin'ny maika indrindra)",
    "agent.sortedByDate": "Milahatra araka ny daty (vaovao indrindra aloha)",
    "agent.byDate": "Alahatra araka ny daty vaovao indrindra",
    "agent.byAI": "Alahatra amin'ny AI - Haavon-doza",
    "agent.inProgressShort": "am-pandehanana",
    "agent.resolvedShort": "voavaha",
    "agent.treatedShort": "voakarakara",
    "agent.reportsShort": "fitarainana",
    "agent.takeCharge": "Handray an-tanana",
    "agent.markResolved": "Marihina fa voavaha",
    "agent.viewMore": "Hijery bebe kokoa",
    "agent.detailsTitle": "Antsipirian'ny fitarainana",
    "agent.locationTitle": "Toerana",
    "agent.getDirections": "Lalana",
    "agent.openInMaps": "Sokafy ao amin'ny Maps",
    "agent.noCoordinates": "Tsy misy toerana GPS amin'ity fitarainana ity",
    "agent.createdOn": "Noforonina ny",
    "agent.latestAssigned": "Fitarainana nomena farany",
    "agent.seeAllShort": "Hijery daholo",
    "common.confirm": "Hamafiso",
    "admin.assignToAgent": "Manendre mpiasa",
    "admin.reportAddress": "Adiresin'ny fitarainana",
    "admin.suggestWithAI": "Manorona amin'ny AI",
    "admin.allAvailableAgents": "Ny mpiasa misy rehetra",
    "admin.aiAnalyzing": "Eo am-pandinihana AI...",
    "admin.seeUrgent": "Hijery ny fitarainana maika rehetra",
    "admin.colName": "Anarana",
    "prof.min6": "litera 6 farafahakeliny",
    "val.passwordMin6": "Tsy maintsy misy litera 6 farafahakeliny ny teny miafina",
    "val.required": "Ilaina ity saha ity",
    "val.titleRequired": "Ilaina ny lohateny",
    "val.titleMin3": "Tsy maintsy misy litera 3 farafahakeliny ny lohateny",
    "val.titleMax100": "Tsy tokony hihoatra ny litera 100 ny lohateny",
    "val.descRequired": "Ilaina ny famaritana",
    "val.descMin10": "Tsy maintsy misy litera 10 farafahakeliny ny famaritana",
    "val.descMax500": "Tsy tokony hihoatra ny litera 500 ny famaritana",
    "val.imageUrlInvalid": "Tsy mety ny URL an'ny sary",
    "val.imageRequired": "Ilaina sary iray farafahakeliny",
    "feed.sendToPrefix": "Alefaso amin'ny",
    "feed.user": "mpampiasa",
    "feed.users": "mpampiasa",
    "feed.sending": "Andefasana...",
    "prof.password": "Teny miafina",
    "prof.dangerZone": "Faritra mampidi-doza",
    "prof.deleteWarning": "Ny famafana ny kaontinao dia tsy azo averina intsony.",
    "prof.deleteAccount": "Fafao ny kaontiko",
    "prof.deleteConfirm": "Azo antoka ve ? Hofafana tanteraka ny kaontinao. Tsy azo averina io hetsika io.",
    "prof.deleteConfirmBtn": "Eny, fafao",
    "prof.deleteError": "Tsy nahomby ny famafana ny kaonty. Andramo indray.",
    "val.invalidFormat": "Endrika diso",
    "val.addressRequired": "Tsy maintsy fenoina ny adiresy",
    "val.addressMin4": "Tsy maintsy misy litera 4 farafahakeliny ny adiresy",
    "val.phoneRequired": "Tsy maintsy fenoina ny laharan-telefaonina",
    "val.phoneFormat": "Ny laharana dia tsy maintsy manomboka amin'ny 032, 033, 034, 037 na 038 ary misy isa 10 marina",
    "val.nameMin2": "Tsy maintsy misy litera 2 farafahakeliny ny anarana",
    "val.emailInvalid": "Mailaka diso (ohatra: anarana@domaine.com)",
    "val.nameRequired": "Tsy maintsy fenoina ny anarana",
    "val.nameNoDigits": "Ny anarana dia tsy tokony hisy isa",
    "val.nameLetters": "Ny anarana dia litera, elanelana na tsipika ihany",
    "val.emailRequired": "Tsy maintsy fenoina ny mailaka",
    "val.emailGmail": "Ny mailaka dia tsy maintsy adiresy @gmail.com",
    "val.emailNoSpaces": "Ny mailaka dia tsy tokony hisy elanelana",
    "val.passwordRequired": "Tsy maintsy fenoina ny teny miafina",
    "auth.oops": "Indrisy !",
    "auth.continue": "Manohy",
    "auth.loginSuccessMsg": "Nahomby ny fidirana ! Tongasoa",
    "auth.accountCreated": "Voaforona soa aman-tsara ny kaontinao ! Afaka miditra ianao izao.",
    "val.addressMin6": "Tsy maintsy misy litera 6 farafahakeliny ny adiresy",
    "val.addressChars": "Ny adiresy dia litera, isa ary elanelana ihany",
    "val.nameNoDigitsDot": "Ny anarana dia tsy tokony hisy isa.",
    "val.nameLettersDot": "Ny anarana dia litera, elanelana na tsipika ihany.",
    "val.selectDomain": "Misafidiana ny sehatra iasanao azafady",
    "val.selectJob": "Misafidiana ny asanao azafady",
    "admin.urgentToTreat": "fitarainana maika hokarakaraina",
    "admin.noUrgent": "Tsy misy fitarainana maika",
    "chat.title": "Hafatra",
    "chat.received": "Hafatra voaray",
    "chat.newMessage": "Hafatra vaovao",
    "chat.noMessage": "Tsy misy hafatra",
    "chat.recipient": "Mpandray",
    "chat.selectRecipient": "Misafidiana mpandray",
    "chat.recipientLocked": "Voahidy ny mpandray (mamaly)",
    "chat.sendType": "Karazana fandefasana",
    "chat.message": "Hafatra",
    "chat.email": "Mailaka",
    "chat.subject": "Lohahevitra",
    "chat.subjectPlaceholder": "Lohahevitry ny hafatra",
    "chat.yourMessage": "Ny hafatrao...",
    "chat.infoCitizen": "💬 Amin'ny maha olom-pirenena anao, ny mpitantana ihany no azonao andefasana hafatra.",
    "chat.infoAgent": "💬 Amin'ny maha mpiasa anao, ny mpitantana ihany no azonao andefasana hafatra.",
    "chat.infoAdmin": "💬 Amin'ny maha mpitantana anao, afaka mandefa hafatra ho an'ny mpampiasa rehetra (olom-pirenena, mpiasa, mpitantana) ianao.",
    "chat.invalidRecipient": "❌ Mpandray diso.",
    "chat.sendReply": "Alefaso ny valiny",
    "chat.sendMessage": "Alefaso ny hafatra",
    "chat.sendEmail": "Alefaso ny mailaka",
    "chat.replyAdminOnly": "Ny hafatry ny mpitantana ihany no azonao valiana.",
    "chat.sendAdminOnly": "Ny mpitantana ihany no azonao andefasana hafatra.",
    "chat.emailSent": "Voalefa soa aman-tsara ny mailaka ! Handray fampandrenesana sy mailaka tena izy ny mpandray.",
    "chat.messageSent": "Voalefa soa aman-tsara ny hafatra !",
    "chat.sendError": "Nisy olana tamin'ny fandefasana",
    "map.title": "🗺️ Sarintanin'ny fitarainana",
    "map.comingSoon": "Ho avy tsy ho ela...",
    "map.subtitle": "Fijerena ny fitarainana amin'ny sarintany mifanentana",
    "mine.empty": "Tsy manana fitarainana ianao",
    "mine.noPosition": "Toerana tsy voafaritra",
    "admin.colTitle": "Lohateny",
    "admin.colType": "Karazana",
    "admin.colLocation": "Toerana",
    "admin.colStatus": "Sata",
    "admin.colDate": "Daty",
    "prof.lastModified": "Fanovana farany :",
    "prof.never": "Tsy mbola",
    "prof.phone": "Finday",
    "admin.dashboardTitle": "Tabilao",
    "admin.export": "Aondrana",
    "admin.totalReports": "Totalin'ny fitarainana",
    "admin.resolutionRate": "Tahan'ny famahana",
    "admin.activeAgents": "Mpiasa mavitrika",
    "admin.byProblemType": "Araka ny karazana olana",
    "admin.urgentReports": "Fitarainana maika",
    "admin.latestReports": "Fitarainana farany",
    "admin.assignAgent": "Manendre mpiasa",
    "admin.assigning": "Manendry...",
    "admin.assign": "Tendreo",
    "admin.personalSpace": "Sehatra manokana",
    "admin.fullNameCaps": "ANARANA FENO",
    "admin.emailCaps": "ADIRESY MAILAKA",
    "admin.roleCaps": "ANDRAIKITRA",
    "admin.changePassword": "Ovay ny teny miafina",
    "admin.encrypted": "Voaaro amin'ny fanafenana AES-256",
    "admin.smartAssignment": "FANENDRENA MAHARY SAINA",
    "admin.aiAssignmentTitle": "Fanendrena amin'ny AI",
    "admin.aiAssignmentSub": "Ny faharanitan-tsaina artifisialy dia mandinika ny fitarainana tsirairay ary manoro ny mpiasa mety indrindra araka ny toerana sy ny fahafahana",
    "admin.allDomains": "Sehatra rehetra",
    "admin.noAgentForType": "Tsy misy mpiasa mahazo an'ity karazana olana ity",
    "admin.aiError": "Nisy olana tamin'ny fanadihadiana AI",
    "admin.assignedTo": "Nomena an'i",
    "admin.assignError": "Nisy olana tamin'ny fanendrena",
    "admin.networkError": "Nisy olana amin'ny fifandraisana",
    "admin.aiFoundPrefix": "Nahita ny AI",
    "admin.agentsWord": "mpiasa",
    "admin.inSameCity": "ao amin'ny tanàna iray",
    "admin.availableWord": "malalaka",
    "admin.userManagement": "Fitantanana ny mpampiasa",
    "admin.agentsWord": "mpiasa",
    "admin.citizensWord": "olom-pirenena",
  },

  en: {
    "app.tagline": "Citizen platform",
    "user.default": "User",

    "nav.home": "Home",
    "nav.report": "Report",
    "nav.profile": "Profile",
    "nav.dashboard": "Dashboard",
    "nav.signalements": "Reports",
    "nav.users": "Users",
    "nav.assignmentIA": "AI Assignment",

    "desc.overview": "Overview",
    "desc.explore": "Explore",
    "desc.new": "New",
    "desc.myAccount": "My account",
    "desc.management": "Management",
    "desc.settings": "Settings",
    "desc.ai": "Artificial intelligence",
    "desc.missions": "My missions",

    "role.admin": "Admin",
    "role.agent": "Agent",
    "role.citizen": "Citizen",
    "roleFull.admin": "Administrator",
    "roleFull.agent": "Field agent",
    "roleFull.citizen": "Citizen",

    "notif.title": "Notifications",
    "notif.refresh": "Refresh",
    "notif.readAll": "Mark all read",
    "notif.empty": "No notifications",

    "menu.logout": "Log out",
    "menu.appearance": "Appearance",
    "menu.language": "Language",
    "menu.light": "Light",
    "menu.dark": "Dark",

    "logout.title": "Log out",
    "logout.question": "Are you sure you want to log out?",
    "common.cancel": "Cancel",
    "common.loading": "Loading",

    "sig.newTitle": "New report",
    "sig.editTitle": "Edit report",
    "sig.subtitle": "Report an issue in Madagascar",
    "sig.titlePlaceholder": "Report title *",
    "sig.descPlaceholder": "Detailed description *",
    "sig.locLabel": "Precise location *",
    "sig.detectGps": "Detect my GPS location",
    "sig.detecting": "Detecting...",
    "sig.manualEntry": "Enter address manually",
    "sig.manualTitle": "Manual entry",
    "sig.quartier": "Neighborhood",
    "sig.street": "Street / Road",
    "sig.city": "City",
    "sig.validateAddress": "Validate address",
    "sig.detected": "Location detected",
    "sig.lowPrecisionWarn": "Low precision: the detected neighborhood may be inaccurate. If it's not correct, use “Enter address manually” to fix it.",
    "sig.lowPrecisionMsg": "Precision is low (common on desktop, where location comes from Wi-Fi). Check the detected neighborhood and correct it if needed with “Enter address manually”.",
    "sig.entered": "Address entered",
    "sig.clear": "Clear",
    "sig.imagesLabel": "Images",
    "sig.atLeastOne": "(at least 1)",
    "sig.takePhoto": "Take a photo",
    "sig.gallery": "Gallery / Files",
    "sig.orUrl": "or via a URL",
    "sig.urlPlaceholder": "Image URL",
    "sig.capture": "Capture",
    "sig.send": "Send",
    "sig.sending": "Sending...",
    "sig.update": "Update",
    "sig.searchPlaceholder": "Search a report...",
    "sig.filterType": "Issue type",
    "sig.filterStatus": "Status",
    "sig.all": "All",
    "sig.reset": "Reset",
    "sig.results": "result(s)",
    "sig.listTitle": "All reports",
    "sig.empty": "No report found",
    "sig.seeMore": "See more",
    "sig.descrTitle": "Description",
    "sig.locationTitle": "Location",
    "sig.date": "Date",
    "sig.author": "Author",
    "sig.edit": "Edit",
    "sig.delete": "Delete",
    "sig.gps": "GPS coordinates",
    "sig.anonymous": "Anonymous",
    "sig.deleteConfirm": "Are you sure you want to delete this report?",
    "sig.close": "Close",
    "sig.success": "Success",
    "sig.info": "Information",
    "sig.confirmation": "Confirmation",
    "sig.createdOk": "✓ Report created successfully!",
    "sig.updatedOk": "✓ Report updated successfully!",
    "sig.deletedOk": "✓ Report deleted successfully!",
    "sig.fixErrors": "Please fix the errors",

    "status.EN_ATTENTE": "Pending",
    "status.EN_COURS": "In progress",
    "status.RESOLU": "Resolved",
    "status.REJETE": "Rejected",
    "status.TRAITE": "Processed",

    "cat.VOIRIE": "Roads",
    "cat.ECLAIRAGE": "Public lighting",
    "cat.PROPRETE": "Cleanliness / Waste",
    "cat.EAU": "Water / Sanitation",
    "cat.ESPACES_VERTS": "Green spaces",
    "cat.TRANSPORTS": "Transport / Mobility",
    "cat.SECURITE": "Safety / Prevention",
    "cat.URBANISME": "Urban planning",

    "feed.reportsWord": "reports",
    "feed.resolved": "Resolved",
    "feed.handling": "Handling",
    "feed.resolution": "Resolution",
    "feed.empty": "No report",
    "feed.beFirst": "Be the first to report an issue",
    "feed.comment": "Comment",
    "feed.share": "Share",
    "feed.noComment": "No comment",
    "feed.writeComment": "Write a comment...",
    "feed.shareTo": "Send to a user",
    "feed.searchUser": "Search a user...",
    "feed.noUser": "No user found",
    "feed.location": "Location",
    "feed.recently": "Recently",
    "feed.selectRecipient": "Please select at least one recipient",

    "prof.title": "My profile",
    "prof.subtitle": "Manage your information",
    "prof.edit": "Edit",
    "prof.save": "Save",
    "prof.loading": "Loading...",
    "prof.fullName": "Full name",
    "prof.email": "Email",
    "prof.fullAddress": "Full address",
    "prof.yourName": "Your name",
    "prof.yourAddress": "Your full address",
    "prof.security": "Security",
    "prof.change": "Change",
    "prof.currentPassword": "Current password",
    "prof.newPassword": "New password",
    "prof.confirmPassword": "Confirm password",
    "prof.addressNotSet": "Address not provided",
    "prof.unknownLocation": "Unknown location",
    "prof.justNow": "Just now",
    "prof.updated": "Profile updated!",
    "prof.passwordChanged": "Password changed!",
    "prof.reportDeleted": "Report deleted!",
    "prof.fixErrors": "Please fix the errors before saving",
    "prof.networkError": "Network error",
    "prof.passwordMismatch": "The passwords do not match",
    "prof.reports": "Reports",
    "prof.myReports": "My reports",
    "prof.personalInfo": "Personal information",
    "prof.notProvided": "Not provided",
    "prof.roleNotEditable": "Role not editable",
    "prof.updateError": "Error during update",
    "prof.passwordChangeError": "Error changing password",
    "prof.deleteReportTitle": "Delete the report",
    "prof.deleteConfirm": "Are you sure you want to delete “{title}”? This action is irreversible.",

    "time.now": "Just now",
    "time.minutes": "{n} min ago",
    "time.hours": "{n} h ago",
    "time.days": "{n} d ago",

    "type.VOIRIE": "Roads",
    "type.ECLAIRAGE": "Lighting",
    "type.DECHETS": "Waste",
    "type.PROPRETE": "Waste",
    "type.EAU": "Water",
    "type.ESPACES_VERTS": "Green",
    "type.SECURITE": "Safety",
    "type.TRANSPORTS": "Transport",
    "type.URBANISME": "Urban",
    "type.AUTRE": "Other",

    "notifT.NOUVEAU_SIGNALEMENT": "New report",
    "notifT.CONFIRMATION_SIGNALEMENT": "Report registered",
    "notifT.ASSIGNATION": "Report assigned",
    "notifT.CHANGEMENT_STATUS": "Update on your report",
    "notifT.AGENT_ASSIGNE": "Agent assigned",
    "notifT.PARTAGE_SIGNALEMENT": "Report shared",
    "notifM.NOUVEAU_SIGNALEMENT": "A new report has been created: {title}",
    "notifM.CONFIRMATION_SIGNALEMENT": "Your report “{title}” has been registered and will be handled shortly.",
    "notifM.ASSIGNATION": "The report “{title}” has been assigned to you.",
    "notifM.AGENT_ASSIGNE": "An agent has been assigned to your report “{title}”: {agent}",
    "notifM.CHANGEMENT_STATUS": "Your report “{title}” {status}",
    "notifM.PARTAGE_SIGNALEMENT": "{sender} shared the report “{title}” with you.",
    "statusPhrase.EN_COURS": "is now being processed",
    "statusPhrase.RESOLU": "has been resolved! Thank you for your contribution.",
    "statusPhrase.REJETE": "has been rejected.",

    "auth.accessBadge": "ACCESS",
    "auth.loginTitle": "Login",
    "auth.loginSubtitle": "Sign in to access your account",
    "auth.email": "Email address",
    "auth.password": "Password",
    "auth.loginBtn": "Sign in",
    "auth.loggingIn": "Signing in...",
    "auth.noAccount": "No account yet?",
    "auth.signup": "Sign up",
    "auth.registerBadge": "SIGN UP",
    "auth.registerTitle": "Create an account",
    "auth.registerSubtitle": "Join the community in just a few seconds",
    "auth.registerBtn": "Create my account",
    "auth.registering": "Signing up...",
    "auth.wrongCredentials": "Incorrect email or password",
    "auth.forgotPassword": "Forgot password?",
    "auth.sending": "Sending...",
    "auth.sendCode": "Send code",
    "auth.resendCode": "Resend",
    "auth.confirm": "Confirm",
    "auth.codePlaceholder": "6-digit code",
    "auth.codeSent": "A verification code has been sent to your email.",
    "auth.codeSendError": "Could not send the code. Try again.",
    "auth.codeInvalid": "Incorrect or expired code.",
    "auth.emailInvalid": "Invalid email address.",
    "auth.emailConfirmed": "Email confirmed",
    "auth.confirmEmailFirst": "Please confirm your email address first.",
    "auth.resetSent": "If an account exists for this address, a reset email has been sent.",
    "reset.title": "New password",
    "reset.subtitle": "Choose a new password for your account.",
    "reset.newPassword": "New password",
    "reset.confirmPassword": "Confirm password",
    "reset.submit": "Reset password",
    "reset.mismatch": "Passwords do not match.",
    "reset.invalidLink": "Invalid or expired link.",
    "reset.error": "Reset failed. Try again.",
    "reset.successTitle": "Password reset!",
    "reset.successMsg": "Redirecting to the login page...",
    "reset.backToLogin": "Back to login",
    "auth.hasAccount": "Already have an account?",
    "auth.login": "Sign in",
    "auth.brandLine1": "Join the",
    "auth.brandLine2": "urban revolution",
    "auth.brandParagraph": "Actively take part in improving your city by reporting problems and contributing to a more responsible community.",
    "auth.statRealtime": "Real time",
    "auth.statTracking": "Tracking",
    "auth.statCommunity": "Community",
    "auth.fullName": "Full name",
    "auth.phone": "Phone",
    "auth.phoneFormat": "Format: 0321234567 (10 digits)",
    "auth.address": "Full address",
    "auth.accountType": "Account type",
    "auth.citizen": "Citizen",
    "auth.agent": "Municipal agent",
    "auth.citizenDesc": "Report problems in your neighborhood",
    "auth.agentDesc": "Manage and resolve citizen reports",
    "auth.interventionDomain": "Field of intervention",
    "auth.yourJob": "Your job",
    "dom.VOIRIE.label": "Roads and infrastructure",
    "dom.VOIRIE.desc": "Roads, sidewalks, potholes",
    "dom.ECLAIRAGE.label": "Public lighting",
    "dom.ECLAIRAGE.desc": "Street lamps, urban lighting",
    "dom.DECHETS.label": "Waste and cleanliness",
    "dom.DECHETS.desc": "Waste collection, cleaning",
    "dom.ESPACES_VERTS.label": "Green spaces",
    "dom.ESPACES_VERTS.desc": "Parks, gardens, trees",
    "dom.TRANSPORTS.label": "Transport and mobility",
    "dom.TRANSPORTS.desc": "Public transport, parking",
    "dom.SECURITE.label": "Safety and prevention",
    "dom.SECURITE.desc": "Public safety, prevention",
    "dom.URBANISME.label": "Urban planning",
    "dom.URBANISME.desc": "Urban development, construction",
    "met.AGENT_VOIRIE.label": "Road worker",
    "met.AGENT_VOIRIE.desc": "Pothole repair, road maintenance",
    "met.TECHNICIEN_GENIE_CIVIL.label": "Civil engineering technician",
    "met.TECHNICIEN_GENIE_CIVIL.desc": "Inspection of bridges, tunnels, structures",
    "met.CHEF_CHANTIER_VOIRIE.label": "Roadworks site manager",
    "met.CHEF_CHANTIER_VOIRIE.desc": "Coordination of road works",
    "met.AGENT_SIGNALISATION.label": "Signage worker",
    "met.AGENT_SIGNALISATION.desc": "Installing and maintaining signs, traffic lights",
    "met.TECHNICIEN_ECLAIRAGE.label": "Lighting technician",
    "met.TECHNICIEN_ECLAIRAGE.desc": "Street lamp repair, network maintenance",
    "met.INGENIEUR_ECLAIRAGE.label": "Urban lighting engineer",
    "met.INGENIEUR_ECLAIRAGE.desc": "Lighting design, energy optimization",
    "met.AGENT_MAINTENANCE_ELEC.label": "Electrical maintenance worker",
    "met.AGENT_MAINTENANCE_ELEC.desc": "Fixing electrical faults",
    "met.AGENT_COLLECTE.label": "Collection worker",
    "met.AGENT_COLLECTE.desc": "Household waste collection",
    "met.TECHNICIEN_NETTOIEMENT.label": "Cleaning technician",
    "met.TECHNICIEN_NETTOIEMENT.desc": "Cleaning streets, public spaces",
    "met.RESPONSABLE_DECHETTERIE.label": "Recycling center manager",
    "met.RESPONSABLE_DECHETTERIE.desc": "Managing waste centers",
    "met.AGENT_TRI.label": "Sorting worker",
    "met.AGENT_TRI.desc": "Waste sorting center",
    "met.COORDINATEUR_PROPRETE.label": "Cleanliness coordinator",
    "met.COORDINATEUR_PROPRETE.desc": "Route planning",
    "met.JARDINIER_MUNICIPAL.label": "Municipal gardener",
    "met.JARDINIER_MUNICIPAL.desc": "Maintaining parks, gardens, beds",
    "met.ELAGUEUR.label": "Tree pruner",
    "met.ELAGUEUR.desc": "Pruning and tree care",
    "met.TECHNICIEN_ESPACES_VERTS.label": "Green space technician",
    "met.TECHNICIEN_ESPACES_VERTS.desc": "Landscaping",
    "met.PAYSAGISTE_URBAIN.label": "Urban landscaper",
    "met.PAYSAGISTE_URBAIN.desc": "Designing green spaces",
    "met.AGENT_ARROSAGE.label": "Irrigation worker",
    "met.AGENT_ARROSAGE.desc": "Managing irrigation systems",
    "met.AGENT_REGULATION.label": "Traffic control worker",
    "met.AGENT_REGULATION.desc": "Managing traffic, lights, jams",
    "met.CONTROLEUR_TRANSPORT.label": "Transport inspector",
    "met.CONTROLEUR_TRANSPORT.desc": "Checking buses, trams, metro",
    "met.TECHNICIEN_STATIONNEMENT.label": "Parking technician",
    "met.TECHNICIEN_STATIONNEMENT.desc": "Managing parking, meters",
    "met.AGENT_MOBILITE_DOUCE.label": "Soft mobility worker",
    "met.AGENT_MOBILITE_DOUCE.desc": "Maintaining bike lanes, stations",
    "met.AGENT_SECURITE_URBAINE.label": "Urban safety officer",
    "met.AGENT_SECURITE_URBAINE.desc": "Neighborhood surveillance",
    "met.POLICE_MUNICIPALE.label": "Municipal police",
    "met.POLICE_MUNICIPALE.desc": "Maintaining public order, fines",
    "met.AGENT_MEDIATEUR.label": "Mediation officer",
    "met.AGENT_MEDIATEUR.desc": "Resolving neighborhood conflicts",
    "met.COORDINATEUR_VIDEO.label": "CCTV coordinator",
    "met.COORDINATEUR_VIDEO.desc": "Camera supervision",
    "met.URBANISTE.label": "Urban planner",
    "met.URBANISTE.desc": "Urban planning",
    "met.ARCHITECTE_CONSEIL.label": "Consulting architect",
    "met.ARCHITECTE_CONSEIL.desc": "Architecture advice",
    "met.TECHNICIEN_URBANISME.label": "Planning technician",
    "met.TECHNICIEN_URBANISME.desc": "Processing building permits",
    "met.CHARGE_MISSION_URBAIN.label": "Urban project officer",
    "met.CHARGE_MISSION_URBAIN.desc": "Development projects",

    "common.error": "Error",
    "common.success": "Success",
    "common.info": "Information",
    "common.limit": "Limit",
    "common.requiredField": "Required field",
    "common.networkError": "Network error",
    "common.genericError": "An error occurred",
    "common.congrats": "Congratulations!",
    "common.search": "Search",
    "agent.welcome": "Welcome to your workspace",
    "agent.toTreat": "Reports to handle",
    "agent.assigned": "Assigned",
    "agent.assignedReports": "Assigned reports",
    "agent.processingReports": "Reports being processed",
    "agent.noAssigned": "No assigned report",
    "agent.allTreated": "All your reports have been handled!",
    "agent.noAssignedYet": "You don't have any reports to handle yet.",
    "agent.noReportsToShow": "No report to display",
    "agent.loadingDashboard": "Loading dashboard...",
    "agent.loadingReports": "Loading reports...",
    "agent.totalActive": "Total active",
    "agent.urgent": "Urgent",
    "agent.important": "Important",
    "agent.moderate": "Moderate",
    "agent.low": "Low",
    "agent.municipalService": "Municipal service",
    "agent.notDefined": "Not defined",
    "agent.noTitle": "Untitled",
    "agent.noDescription": "No description",
    "agent.locationUnspecified": "Location not specified",
    "agent.unknownDate": "Unknown date",
    "agent.unknown": "Unknown",
    "agent.proofTitle": "Proof of resolution",
    "agent.proofIntro": "Please provide proof that the problem has been resolved.",
    "agent.proofDescLabel": "Resolution description",
    "agent.proofDescPlaceholder": "Describe how the problem was resolved...",
    "agent.beforeAfter": "Before/after photos",
    "agent.clickAddPhotos": "Click to add photos",
    "agent.cantLoadReports": "Unable to load reports",
    "agent.cantReachServer": "Unable to reach the server",
    "agent.takenCharge": "Report taken in charge!",
    "agent.cantTakeCharge": "Unable to take in charge",
    "agent.max5photos": "5 photos maximum",
    "agent.cantLoadImages": "Unable to load images",
    "agent.addDescription": "Add a description",
    "agent.proofSendError": "Error sending the proof",
    "agent.statusUpdateError": "Error updating the status",
    "agent.reportResolved": "Report resolved!",
    "agent.resolvedReports": "Resolved reports",
    "agent.resolvedSubtitle": "View the resolution proofs of reports",
    "agent.totalResolved": "Total resolved",
    "agent.myResolution": "My resolution",
    "agent.searchResolvedPlaceholder": "Search by title, description or address...",
    "agent.noneResolvedYet": "You haven't resolved any report yet",
    "agent.noResolvedFound": "No resolved report found",
    "agent.resolvedBy": "Resolved by:",
    "agent.seeLess": "See less",
    "agent.seeProofs": "See resolution proofs",
    "agent.noImageForProof": "No image for this proof",
    "agent.noProofRecorded": "No intervention proof recorded",

    "admin.overview": "Overview of the SmartCity platform",
    "admin.unspecified": "Unspecified",
    "admin.cantFetchReports": "Unable to fetch reports",
    "admin.loadDataError": "Error while loading data",
    "admin.selectAgent": "Please select an agent",
    "admin.cantAssign": "Unable to assign",
    "admin.assignNetworkError": "Network error during assignment",
    "admin.fillAllFields": "Please fill in all fields",
    "admin.addError": "Error while adding",
    "admin.printPreview": "Print preview",
    "admin.pdfPrint": "PDF / Print",
    "admin.topAgents": "Top Agents",
    "admin.topAgentsSub": "Ranked by handled reports (in progress + resolved)",
    "admin.noActiveAgent": "No active agent at the moment",
    "admin.topCitizens": "Top Citizens",
    "admin.topCitizensSub": "Ranked by created reports",
    "admin.noActiveCitizen": "No active citizen at the moment",
    "admin.allAgents": "All agents",
    "admin.allCitizens": "All citizens",
    "admin.email": "Email",
    "admin.phone": "Phone",
    "admin.domain": "Domain",
    "admin.job": "Job",
    "admin.totalHandled": "Total handled",
    "admin.signupDate": "Signup date",
    "admin.accessDenied": "Access Denied",
    "admin.adminOnly": "This page is reserved for administrators.",
    "admin.aiSuggestions": "AI Suggestions",
    "admin.aiPriority": "Priority: geographic + availability",
    "admin.noAgentForDomain": "No agent available for this domain",
    "admin.pendingReports": "Pending reports",
    "admin.availableAgents": "Available agents",
    "admin.expertiseDomains": "Expertise domains",
    "admin.searchToAssign": "Search a report by title, description, neighborhood or city...",
    "admin.noReportToAssign": "No report to assign",
    "admin.allAssignedOrResolved": "All reports have been assigned or resolved",
    "admin.citizenReports": "Citizen reports",
    "admin.citizenReportsSub": "View all problems reported by the community",
    "admin.searchByTitle": "Search by title, description or location...",
    "admin.filters": "Filters",
    "admin.publishDate": "Publish date",
    "admin.publishedBy": "Published by",
    "agent.dashboardTitle": "Agent Dashboard",
    "agent.assignedCaps": "ASSIGNED REPORTS",
    "agent.seeAll": "See all",
    "agent.toTakeCharge": "To take in charge",
    "agent.activeReports": "ACTIVE REPORTS",
    "agent.sortedByDanger": "Sorted by danger level (most urgent to least urgent)",
    "agent.sortedByDate": "Sorted by date (most recent to oldest)",
    "agent.byDate": "Sorted by most recent date",
    "agent.byAI": "Sorted by AI - Danger level",
    "agent.inProgressShort": "in progress",
    "agent.resolvedShort": "resolved",
    "agent.treatedShort": "handled",
    "agent.reportsShort": "reports",
    "agent.takeCharge": "Take in charge",
    "agent.markResolved": "Mark resolved",
    "agent.viewMore": "View more",
    "agent.detailsTitle": "Report details",
    "agent.locationTitle": "Location",
    "agent.getDirections": "Directions",
    "agent.openInMaps": "Open in Maps",
    "agent.noCoordinates": "GPS coordinates not available for this report",
    "agent.createdOn": "Created on",
    "agent.latestAssigned": "Latest assigned reports",
    "agent.seeAllShort": "See all",
    "common.confirm": "Confirm",
    "admin.assignToAgent": "Assign to an agent",
    "admin.reportAddress": "Report address",
    "admin.suggestWithAI": "Suggest with AI",
    "admin.allAvailableAgents": "All available agents",
    "admin.aiAnalyzing": "AI analysis in progress...",
    "admin.seeUrgent": "See all urgent reports",
    "admin.colName": "Name",
    "prof.min6": "at least 6 characters",
    "val.passwordMin6": "Password must contain at least 6 characters",
    "val.required": "This field is required",
    "val.titleRequired": "Title is required",
    "val.titleMin3": "Title must be at least 3 characters",
    "val.titleMax100": "Title must not exceed 100 characters",
    "val.descRequired": "Description is required",
    "val.descMin10": "Description must be at least 10 characters",
    "val.descMax500": "Description must not exceed 500 characters",
    "val.imageUrlInvalid": "The image URL is not valid",
    "val.imageRequired": "At least one image is required",
    "feed.sendToPrefix": "Send to",
    "feed.user": "user",
    "feed.users": "users",
    "feed.sending": "Sending...",
    "prof.password": "Password",
    "prof.dangerZone": "Danger zone",
    "prof.deleteWarning": "Deleting your account is permanent and irreversible.",
    "prof.deleteAccount": "Delete my account",
    "prof.deleteConfirm": "Are you sure? Your account will be permanently deleted. This action is irreversible.",
    "prof.deleteConfirmBtn": "Yes, delete",
    "prof.deleteError": "Account deletion failed. Please try again.",
    "val.invalidFormat": "Invalid format",
    "val.addressRequired": "Address is required",
    "val.addressMin4": "Address must contain at least 4 characters",
    "val.phoneRequired": "Phone number is required",
    "val.phoneFormat": "Phone must start with 032, 033, 034, 037 or 038 and contain exactly 10 digits",
    "val.nameMin2": "Name must contain at least 2 characters",
    "val.emailInvalid": "Invalid email (example: name@domain.com)",
    "val.nameRequired": "Name is required",
    "val.nameNoDigits": "Name must not contain digits",
    "val.nameLetters": "Name may only contain letters, spaces or hyphens",
    "val.emailRequired": "Email is required",
    "val.emailGmail": "Email must be a @gmail.com address",
    "val.emailNoSpaces": "Email must not contain spaces",
    "val.passwordRequired": "Password is required",
    "auth.oops": "Oops!",
    "auth.continue": "Continue",
    "auth.loginSuccessMsg": "Login successful! Welcome",
    "auth.accountCreated": "Your account has been created successfully! You can now log in.",
    "val.addressMin6": "Address must contain at least 6 characters",
    "val.addressChars": "Address may only contain letters, digits and spaces",
    "val.nameNoDigitsDot": "Name must not contain digits.",
    "val.nameLettersDot": "Name may only contain letters, spaces or hyphens.",
    "val.selectDomain": "Please select your field of intervention",
    "val.selectJob": "Please select your job",
    "admin.urgentToTreat": "urgent report(s) to handle",
    "admin.noUrgent": "No urgent report",
    "chat.title": "Messages",
    "chat.received": "Received messages",
    "chat.newMessage": "New message",
    "chat.noMessage": "No message",
    "chat.recipient": "Recipient",
    "chat.selectRecipient": "Select a recipient",
    "chat.recipientLocked": "Recipient locked (replying)",
    "chat.sendType": "Send type",
    "chat.message": "Message",
    "chat.email": "Email",
    "chat.subject": "Subject",
    "chat.subjectPlaceholder": "Message subject",
    "chat.yourMessage": "Your message...",
    "chat.infoCitizen": "💬 As a citizen, you can only send messages to administrators.",
    "chat.infoAgent": "💬 As an agent, you can only send messages to administrators.",
    "chat.infoAdmin": "💬 As an administrator, you can send messages to all users (citizens, agents, admins).",
    "chat.invalidRecipient": "❌ Invalid recipient.",
    "chat.sendReply": "Send reply",
    "chat.sendMessage": "Send message",
    "chat.sendEmail": "Send email",
    "chat.replyAdminOnly": "You can only reply to messages from administrators.",
    "chat.sendAdminOnly": "You can only send messages to administrators.",
    "chat.emailSent": "Email sent successfully! The recipient will receive a notification and a real email.",
    "chat.messageSent": "Message sent successfully!",
    "chat.sendError": "Error while sending",
    "map.title": "🗺️ Reports map",
    "map.comingSoon": "Coming soon...",
    "map.subtitle": "View reports on an interactive map",
    "mine.empty": "You have no report",
    "mine.noPosition": "Position not defined",
    "admin.colTitle": "Title",
    "admin.colType": "Type",
    "admin.colLocation": "Location",
    "admin.colStatus": "Status",
    "admin.colDate": "Date",
    "prof.lastModified": "Last modified:",
    "prof.never": "Never",
    "prof.phone": "Phone",
    "admin.dashboardTitle": "Dashboard",
    "admin.export": "Export",
    "admin.totalReports": "Total reports",
    "admin.resolutionRate": "Resolution rate",
    "admin.activeAgents": "Active agents",
    "admin.byProblemType": "By problem type",
    "admin.urgentReports": "Urgent reports",
    "admin.latestReports": "Latest reports",
    "admin.assignAgent": "Assign an agent",
    "admin.assigning": "Assigning...",
    "admin.assign": "Assign",
    "admin.personalSpace": "Personal Space",
    "admin.fullNameCaps": "FULL NAME",
    "admin.emailCaps": "EMAIL ADDRESS",
    "admin.roleCaps": "ROLE",
    "admin.changePassword": "Change password",
    "admin.encrypted": "Protected with AES-256 encryption",
    "admin.smartAssignment": "SMART ASSIGNMENT",
    "admin.aiAssignmentTitle": "AI Assignment",
    "admin.aiAssignmentSub": "The artificial intelligence analyzes each report and suggests the most suitable agent based on location and availability",
    "admin.allDomains": "All domains",
    "admin.noAgentForType": "No agent available for this type of issue",
    "admin.aiError": "Error during AI analysis",
    "admin.assignedTo": "Report assigned to",
    "admin.assignError": "Error during assignment",
    "admin.networkError": "Network error",
    "admin.aiFoundPrefix": "AI found",
    "admin.agentsWord": "agent(s)",
    "admin.inSameCity": "in the same city",
    "admin.availableWord": "available",
    "admin.userManagement": "User management",
    "admin.agentsWord": "agents",
    "admin.citizensWord": "citizens",
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem("lang") || "fr");

  useEffect(() => {
    localStorage.setItem("lang", lang);
    document.documentElement.lang = lang;
  }, [lang]);

  const t = (key) => {
    const dict = translations[lang] || translations.fr;
    return dict[key] ?? translations.fr[key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, languages: LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useI18n() {
  const ctx = useContext(LanguageContext);
  return ctx || { lang: "fr", setLang: () => {}, t: (k) => k, languages: LANGUAGES };
}
