# Base de données
spring.datasource.url=jdbc:postgresql://localhost:5432/City
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuration Email avec Brevo
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=genitahrazafindrasoa@gmail.com
spring.mail.password=xsmtpsib-4dbd8a73114ebaeeb2ad839542984e085aa1da7a02046488b28e6acff776139d-nrbU5ZfVzVWeZyXs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Frontend URL pour les liens
app.frontend.url=http://localhost:5173